// Code generated by ent, DO NOT EDIT.

package activityreward

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the activityreward type in the database.
	Label = "activity_reward"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldRewardType holds the string denoting the reward_type field in the database.
	FieldRewardType = "reward_type"
	// FieldRewardValue holds the string denoting the reward_value field in the database.
	FieldRewardValue = "reward_value"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldProbability holds the string denoting the probability field in the database.
	FieldProbability = "probability"
	// FieldTotalStock holds the string denoting the total_stock field in the database.
	FieldTotalStock = "total_stock"
	// FieldRemainingStock holds the string denoting the remaining_stock field in the database.
	FieldRemainingStock = "remaining_stock"
	// FieldTier holds the string denoting the tier field in the database.
	FieldTier = "tier"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldDistributedCount holds the string denoting the distributed_count field in the database.
	FieldDistributedCount = "distributed_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeActivity holds the string denoting the activity edge name in mutations.
	EdgeActivity = "activity"
	// EdgeParticipations holds the string denoting the participations edge name in mutations.
	EdgeParticipations = "participations"
	// Table holds the table name of the activityreward in the database.
	Table = "activity_rewards"
	// ActivityTable is the table that holds the activity relation/edge.
	ActivityTable = "activity_rewards"
	// ActivityInverseTable is the table name for the Activity entity.
	// It exists in this package in order to avoid circular dependency with the "activity" package.
	ActivityInverseTable = "activities"
	// ActivityColumn is the table column denoting the activity relation/edge.
	ActivityColumn = "activity_id"
	// ParticipationsTable is the table that holds the participations relation/edge.
	ParticipationsTable = "activity_participations"
	// ParticipationsInverseTable is the table name for the ActivityParticipation entity.
	// It exists in this package in order to avoid circular dependency with the "activityparticipation" package.
	ParticipationsInverseTable = "activity_participations"
	// ParticipationsColumn is the table column denoting the participations relation/edge.
	ParticipationsColumn = "reward_id"
)

// Columns holds all SQL columns for activityreward fields.
var Columns = []string{
	FieldID,
	FieldActivityID,
	FieldName,
	FieldDescription,
	FieldIcon,
	FieldRewardType,
	FieldRewardValue,
	FieldWeight,
	FieldProbability,
	FieldTotalStock,
	FieldRemainingStock,
	FieldTier,
	FieldStatus,
	FieldSortOrder,
	FieldDistributedCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultIcon holds the default value on creation for the "icon" field.
	DefaultIcon string
	// DefaultRewardValue holds the default value on creation for the "reward_value" field.
	DefaultRewardValue string
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultTotalStock holds the default value on creation for the "total_stock" field.
	DefaultTotalStock int64
	// DefaultRemainingStock holds the default value on creation for the "remaining_stock" field.
	DefaultRemainingStock int64
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultDistributedCount holds the default value on creation for the "distributed_count" field.
	DefaultDistributedCount int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// RewardType defines the type for the "reward_type" enum field.
type RewardType string

// RewardType values.
const (
	RewardTypeBalance      RewardType = "balance"
	RewardTypeSubscription RewardType = "subscription"
	RewardTypeCoupon       RewardType = "coupon"
	RewardTypePoints       RewardType = "points"
	RewardTypeCustom       RewardType = "custom"
)

func (rt RewardType) String() string {
	return string(rt)
}

// RewardTypeValidator is a validator for the "reward_type" field enum values. It is called by the builders before save.
func RewardTypeValidator(rt RewardType) error {
	switch rt {
	case RewardTypeBalance, RewardTypeSubscription, RewardTypeCoupon, RewardTypePoints, RewardTypeCustom:
		return nil
	default:
		return fmt.Errorf("activityreward: invalid enum value for reward_type field: %q", rt)
	}
}

// Tier defines the type for the "tier" enum field.
type Tier string

// TierCommon is the default value of the Tier enum.
const DefaultTier = TierCommon

// Tier values.
const (
	TierGrand       Tier = "grand"
	TierFirst       Tier = "first"
	TierSecond      Tier = "second"
	TierThird       Tier = "third"
	TierCommon      Tier = "common"
	TierConsolation Tier = "consolation"
)

func (t Tier) String() string {
	return string(t)
}

// TierValidator is a validator for the "tier" field enum values. It is called by the builders before save.
func TierValidator(t Tier) error {
	switch t {
	case TierGrand, TierFirst, TierSecond, TierThird, TierCommon, TierConsolation:
		return nil
	default:
		return fmt.Errorf("activityreward: invalid enum value for tier field: %q", t)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive     Status = "active"
	StatusInactive   Status = "inactive"
	StatusOutOfStock Status = "out_of_stock"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusOutOfStock:
		return nil
	default:
		return fmt.Errorf("activityreward: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ActivityReward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByRewardType orders the results by the reward_type field.
func ByRewardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardType, opts...).ToFunc()
}

// ByRewardValue orders the results by the reward_value field.
func ByRewardValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardValue, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByProbability orders the results by the probability field.
func ByProbability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbability, opts...).ToFunc()
}

// ByTotalStock orders the results by the total_stock field.
func ByTotalStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalStock, opts...).ToFunc()
}

// ByRemainingStock orders the results by the remaining_stock field.
func ByRemainingStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemainingStock, opts...).ToFunc()
}

// ByTier orders the results by the tier field.
func ByTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTier, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByDistributedCount orders the results by the distributed_count field.
func ByDistributedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistributedCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActivityField orders the results by activity field.
func ByActivityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivityStep(), sql.OrderByField(field, opts...))
	}
}

// ByParticipationsCount orders the results by participations count.
func ByParticipationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParticipationsStep(), opts...)
	}
}

// ByParticipations orders the results by participations terms.
func ByParticipations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParticipationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newActivityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
	)
}
func newParticipationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParticipationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ParticipationsTable, ParticipationsColumn),
	)
}
