// Code generated by ent, DO NOT EDIT.

package activityreward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldID, id))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldActivityID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldDescription, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldIcon, v))
}

// RewardValue applies equality check predicate on the "reward_value" field. It's identical to RewardValueEQ.
func RewardValue(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldRewardValue, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldWeight, v))
}

// Probability applies equality check predicate on the "probability" field. It's identical to ProbabilityEQ.
func Probability(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldProbability, v))
}

// TotalStock applies equality check predicate on the "total_stock" field. It's identical to TotalStockEQ.
func TotalStock(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldTotalStock, v))
}

// RemainingStock applies equality check predicate on the "remaining_stock" field. It's identical to RemainingStockEQ.
func RemainingStock(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldRemainingStock, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldSortOrder, v))
}

// DistributedCount applies equality check predicate on the "distributed_count" field. It's identical to DistributedCountEQ.
func DistributedCount(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldDistributedCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldUpdatedAt, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldActivityID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContainsFold(FieldDescription, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasSuffix(FieldIcon, v))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContainsFold(FieldIcon, v))
}

// RewardTypeEQ applies the EQ predicate on the "reward_type" field.
func RewardTypeEQ(v RewardType) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldRewardType, v))
}

// RewardTypeNEQ applies the NEQ predicate on the "reward_type" field.
func RewardTypeNEQ(v RewardType) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldRewardType, v))
}

// RewardTypeIn applies the In predicate on the "reward_type" field.
func RewardTypeIn(vs ...RewardType) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldRewardType, vs...))
}

// RewardTypeNotIn applies the NotIn predicate on the "reward_type" field.
func RewardTypeNotIn(vs ...RewardType) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldRewardType, vs...))
}

// RewardValueEQ applies the EQ predicate on the "reward_value" field.
func RewardValueEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldRewardValue, v))
}

// RewardValueNEQ applies the NEQ predicate on the "reward_value" field.
func RewardValueNEQ(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldRewardValue, v))
}

// RewardValueIn applies the In predicate on the "reward_value" field.
func RewardValueIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldRewardValue, vs...))
}

// RewardValueNotIn applies the NotIn predicate on the "reward_value" field.
func RewardValueNotIn(vs ...string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldRewardValue, vs...))
}

// RewardValueGT applies the GT predicate on the "reward_value" field.
func RewardValueGT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldRewardValue, v))
}

// RewardValueGTE applies the GTE predicate on the "reward_value" field.
func RewardValueGTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldRewardValue, v))
}

// RewardValueLT applies the LT predicate on the "reward_value" field.
func RewardValueLT(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldRewardValue, v))
}

// RewardValueLTE applies the LTE predicate on the "reward_value" field.
func RewardValueLTE(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldRewardValue, v))
}

// RewardValueContains applies the Contains predicate on the "reward_value" field.
func RewardValueContains(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContains(FieldRewardValue, v))
}

// RewardValueHasPrefix applies the HasPrefix predicate on the "reward_value" field.
func RewardValueHasPrefix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasPrefix(FieldRewardValue, v))
}

// RewardValueHasSuffix applies the HasSuffix predicate on the "reward_value" field.
func RewardValueHasSuffix(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldHasSuffix(FieldRewardValue, v))
}

// RewardValueEqualFold applies the EqualFold predicate on the "reward_value" field.
func RewardValueEqualFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEqualFold(FieldRewardValue, v))
}

// RewardValueContainsFold applies the ContainsFold predicate on the "reward_value" field.
func RewardValueContainsFold(v string) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldContainsFold(FieldRewardValue, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldWeight, v))
}

// ProbabilityEQ applies the EQ predicate on the "probability" field.
func ProbabilityEQ(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldProbability, v))
}

// ProbabilityNEQ applies the NEQ predicate on the "probability" field.
func ProbabilityNEQ(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldProbability, v))
}

// ProbabilityIn applies the In predicate on the "probability" field.
func ProbabilityIn(vs ...float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldProbability, vs...))
}

// ProbabilityNotIn applies the NotIn predicate on the "probability" field.
func ProbabilityNotIn(vs ...float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldProbability, vs...))
}

// ProbabilityGT applies the GT predicate on the "probability" field.
func ProbabilityGT(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldProbability, v))
}

// ProbabilityGTE applies the GTE predicate on the "probability" field.
func ProbabilityGTE(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldProbability, v))
}

// ProbabilityLT applies the LT predicate on the "probability" field.
func ProbabilityLT(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldProbability, v))
}

// ProbabilityLTE applies the LTE predicate on the "probability" field.
func ProbabilityLTE(v float64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldProbability, v))
}

// ProbabilityIsNil applies the IsNil predicate on the "probability" field.
func ProbabilityIsNil() predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIsNull(FieldProbability))
}

// ProbabilityNotNil applies the NotNil predicate on the "probability" field.
func ProbabilityNotNil() predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotNull(FieldProbability))
}

// TotalStockEQ applies the EQ predicate on the "total_stock" field.
func TotalStockEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldTotalStock, v))
}

// TotalStockNEQ applies the NEQ predicate on the "total_stock" field.
func TotalStockNEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldTotalStock, v))
}

// TotalStockIn applies the In predicate on the "total_stock" field.
func TotalStockIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldTotalStock, vs...))
}

// TotalStockNotIn applies the NotIn predicate on the "total_stock" field.
func TotalStockNotIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldTotalStock, vs...))
}

// TotalStockGT applies the GT predicate on the "total_stock" field.
func TotalStockGT(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldTotalStock, v))
}

// TotalStockGTE applies the GTE predicate on the "total_stock" field.
func TotalStockGTE(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldTotalStock, v))
}

// TotalStockLT applies the LT predicate on the "total_stock" field.
func TotalStockLT(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldTotalStock, v))
}

// TotalStockLTE applies the LTE predicate on the "total_stock" field.
func TotalStockLTE(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldTotalStock, v))
}

// RemainingStockEQ applies the EQ predicate on the "remaining_stock" field.
func RemainingStockEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldRemainingStock, v))
}

// RemainingStockNEQ applies the NEQ predicate on the "remaining_stock" field.
func RemainingStockNEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldRemainingStock, v))
}

// RemainingStockIn applies the In predicate on the "remaining_stock" field.
func RemainingStockIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldRemainingStock, vs...))
}

// RemainingStockNotIn applies the NotIn predicate on the "remaining_stock" field.
func RemainingStockNotIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldRemainingStock, vs...))
}

// RemainingStockGT applies the GT predicate on the "remaining_stock" field.
func RemainingStockGT(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldRemainingStock, v))
}

// RemainingStockGTE applies the GTE predicate on the "remaining_stock" field.
func RemainingStockGTE(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldRemainingStock, v))
}

// RemainingStockLT applies the LT predicate on the "remaining_stock" field.
func RemainingStockLT(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldRemainingStock, v))
}

// RemainingStockLTE applies the LTE predicate on the "remaining_stock" field.
func RemainingStockLTE(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldRemainingStock, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v Tier) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v Tier) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...Tier) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...Tier) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldTier, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldStatus, vs...))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldSortOrder, v))
}

// DistributedCountEQ applies the EQ predicate on the "distributed_count" field.
func DistributedCountEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldDistributedCount, v))
}

// DistributedCountNEQ applies the NEQ predicate on the "distributed_count" field.
func DistributedCountNEQ(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldDistributedCount, v))
}

// DistributedCountIn applies the In predicate on the "distributed_count" field.
func DistributedCountIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldDistributedCount, vs...))
}

// DistributedCountNotIn applies the NotIn predicate on the "distributed_count" field.
func DistributedCountNotIn(vs ...int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldDistributedCount, vs...))
}

// DistributedCountGT applies the GT predicate on the "distributed_count" field.
func DistributedCountGT(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldDistributedCount, v))
}

// DistributedCountGTE applies the GTE predicate on the "distributed_count" field.
func DistributedCountGTE(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldDistributedCount, v))
}

// DistributedCountLT applies the LT predicate on the "distributed_count" field.
func DistributedCountLT(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldDistributedCount, v))
}

// DistributedCountLTE applies the LTE predicate on the "distributed_count" field.
func DistributedCountLTE(v int64) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldDistributedCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ActivityReward {
	return predicate.ActivityReward(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasActivity applies the HasEdge predicate on the "activity" edge.
func HasActivity() predicate.ActivityReward {
	return predicate.ActivityReward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivityWith applies the HasEdge predicate on the "activity" edge with a given conditions (other predicates).
func HasActivityWith(preds ...predicate.Activity) predicate.ActivityReward {
	return predicate.ActivityReward(func(s *sql.Selector) {
		step := newActivityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParticipations applies the HasEdge predicate on the "participations" edge.
func HasParticipations() predicate.ActivityReward {
	return predicate.ActivityReward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ParticipationsTable, ParticipationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParticipationsWith applies the HasEdge predicate on the "participations" edge with a given conditions (other predicates).
func HasParticipationsWith(preds ...predicate.ActivityParticipation) predicate.ActivityReward {
	return predicate.ActivityReward(func(s *sql.Selector) {
		step := newParticipationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActivityReward) predicate.ActivityReward {
	return predicate.ActivityReward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActivityReward) predicate.ActivityReward {
	return predicate.ActivityReward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActivityReward) predicate.ActivityReward {
	return predicate.ActivityReward(sql.NotPredicates(p))
}
