// Code generated by ent, DO NOT EDIT.

package activity

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the activity type in the database.
	Label = "activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldVisibilityRules holds the string denoting the visibility_rules field in the database.
	FieldVisibilityRules = "visibility_rules"
	// FieldParticipationConfig holds the string denoting the participation_config field in the database.
	FieldParticipationConfig = "participation_config"
	// FieldActivityConfig holds the string denoting the activity_config field in the database.
	FieldActivityConfig = "activity_config"
	// FieldTotalParticipations holds the string denoting the total_participations field in the database.
	FieldTotalParticipations = "total_participations"
	// FieldTotalRewardsDistributed holds the string denoting the total_rewards_distributed field in the database.
	FieldTotalRewardsDistributed = "total_rewards_distributed"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRewards holds the string denoting the rewards edge name in mutations.
	EdgeRewards = "rewards"
	// EdgeParticipations holds the string denoting the participations edge name in mutations.
	EdgeParticipations = "participations"
	// Table holds the table name of the activity in the database.
	Table = "activities"
	// RewardsTable is the table that holds the rewards relation/edge.
	RewardsTable = "activity_rewards"
	// RewardsInverseTable is the table name for the ActivityReward entity.
	// It exists in this package in order to avoid circular dependency with the "activityreward" package.
	RewardsInverseTable = "activity_rewards"
	// RewardsColumn is the table column denoting the rewards relation/edge.
	RewardsColumn = "activity_id"
	// ParticipationsTable is the table that holds the participations relation/edge.
	ParticipationsTable = "activity_participations"
	// ParticipationsInverseTable is the table name for the ActivityParticipation entity.
	// It exists in this package in order to avoid circular dependency with the "activityparticipation" package.
	ParticipationsInverseTable = "activity_participations"
	// ParticipationsColumn is the table column denoting the participations relation/edge.
	ParticipationsColumn = "activity_id"
)

// Columns holds all SQL columns for activity fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldIcon,
	FieldType,
	FieldStatus,
	FieldSortOrder,
	FieldStartsAt,
	FieldEndsAt,
	FieldVisibilityRules,
	FieldParticipationConfig,
	FieldActivityConfig,
	FieldTotalParticipations,
	FieldTotalRewardsDistributed,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultIcon holds the default value on creation for the "icon" field.
	DefaultIcon string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultTotalParticipations holds the default value on creation for the "total_participations" field.
	DefaultTotalParticipations int64
	// DefaultTotalRewardsDistributed holds the default value on creation for the "total_rewards_distributed" field.
	DefaultTotalRewardsDistributed int64
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeCheckIn     Type = "check_in"
	TypeLottery     Type = "lottery"
	TypeRedeem      Type = "redeem"
	TypeTask        Type = "task"
	TypeNewbie      Type = "newbie"
	TypeLimitedTime Type = "limited_time"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeCheckIn, TypeLottery, TypeRedeem, TypeTask, TypeNewbie, TypeLimitedTime:
		return nil
	default:
		return fmt.Errorf("activity: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusDraft is the default value of the Status enum.
const DefaultStatus = StatusDraft

// Status values.
const (
	StatusDraft    Status = "draft"
	StatusActive   Status = "active"
	StatusPaused   Status = "paused"
	StatusEnded    Status = "ended"
	StatusArchived Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusActive, StatusPaused, StatusEnded, StatusArchived:
		return nil
	default:
		return fmt.Errorf("activity: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Activity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByTotalParticipations orders the results by the total_participations field.
func ByTotalParticipations(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalParticipations, opts...).ToFunc()
}

// ByTotalRewardsDistributed orders the results by the total_rewards_distributed field.
func ByTotalRewardsDistributed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRewardsDistributed, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRewardsCount orders the results by rewards count.
func ByRewardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRewardsStep(), opts...)
	}
}

// ByRewards orders the results by rewards terms.
func ByRewards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRewardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByParticipationsCount orders the results by participations count.
func ByParticipationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParticipationsStep(), opts...)
	}
}

// ByParticipations orders the results by participations terms.
func ByParticipations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParticipationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRewardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RewardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RewardsTable, RewardsColumn),
	)
}
func newParticipationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParticipationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ParticipationsTable, ParticipationsColumn),
	)
}
