// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/activity"
)

// Activity is the model entity for the Activity schema.
type Activity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 活动名称
	Name string `json:"name,omitempty"`
	// 活动描述
	Description string `json:"description,omitempty"`
	// 活动图标URL或icon名称
	Icon string `json:"icon,omitempty"`
	// 活动类型: check_in=签到, lottery=抽奖, redeem=兑换, task=任务, newbie=新手礼包, limited_time=限时活动
	Type activity.Type `json:"type,omitempty"`
	// 活动状态
	Status activity.Status `json:"status,omitempty"`
	// 排序权重，越大越靠前
	SortOrder int `json:"sort_order,omitempty"`
	// 活动开始时间，null表示立即开始
	StartsAt *time.Time `json:"starts_at,omitempty"`
	// 活动结束时间，null表示永久有效
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// 可见性规则 {user_tags:[],min_balance:0,subscription_required:bool,min_register_days:0}
	VisibilityRules map[string]interface{} `json:"visibility_rules,omitempty"`
	// 参与配置 {max_per_day:1,max_per_week:7,max_per_month:30,max_total:0,cost_balance:0}
	ParticipationConfig map[string]interface{} `json:"participation_config,omitempty"`
	// 活动特定配置，根据type不同而不同
	ActivityConfig map[string]interface{} `json:"activity_config,omitempty"`
	// 总参与次数
	TotalParticipations int64 `json:"total_participations,omitempty"`
	// 总发放奖励次数
	TotalRewardsDistributed int64 `json:"total_rewards_distributed,omitempty"`
	// 创建者
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityQuery when eager-loading is set.
	Edges        ActivityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActivityEdges holds the relations/edges for other nodes in the graph.
type ActivityEdges struct {
	// Rewards holds the value of the rewards edge.
	Rewards []*ActivityReward `json:"rewards,omitempty"`
	// Participations holds the value of the participations edge.
	Participations []*ActivityParticipation `json:"participations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RewardsOrErr returns the Rewards value or an error if the edge
// was not loaded in eager-loading.
func (e ActivityEdges) RewardsOrErr() ([]*ActivityReward, error) {
	if e.loadedTypes[0] {
		return e.Rewards, nil
	}
	return nil, &NotLoadedError{edge: "rewards"}
}

// ParticipationsOrErr returns the Participations value or an error if the edge
// was not loaded in eager-loading.
func (e ActivityEdges) ParticipationsOrErr() ([]*ActivityParticipation, error) {
	if e.loadedTypes[1] {
		return e.Participations, nil
	}
	return nil, &NotLoadedError{edge: "participations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Activity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activity.FieldVisibilityRules, activity.FieldParticipationConfig, activity.FieldActivityConfig:
			values[i] = new([]byte)
		case activity.FieldID, activity.FieldSortOrder, activity.FieldTotalParticipations, activity.FieldTotalRewardsDistributed:
			values[i] = new(sql.NullInt64)
		case activity.FieldName, activity.FieldDescription, activity.FieldIcon, activity.FieldType, activity.FieldStatus, activity.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case activity.FieldStartsAt, activity.FieldEndsAt, activity.FieldCreatedAt, activity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Activity fields.
func (_m *Activity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case activity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case activity.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case activity.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case activity.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = activity.Type(value.String)
			}
		case activity.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = activity.Status(value.String)
			}
		case activity.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case activity.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = new(time.Time)
				*_m.StartsAt = value.Time
			}
		case activity.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = new(time.Time)
				*_m.EndsAt = value.Time
			}
		case activity.FieldVisibilityRules:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field visibility_rules", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.VisibilityRules); err != nil {
					return fmt.Errorf("unmarshal field visibility_rules: %w", err)
				}
			}
		case activity.FieldParticipationConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field participation_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParticipationConfig); err != nil {
					return fmt.Errorf("unmarshal field participation_config: %w", err)
				}
			}
		case activity.FieldActivityConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field activity_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ActivityConfig); err != nil {
					return fmt.Errorf("unmarshal field activity_config: %w", err)
				}
			}
		case activity.FieldTotalParticipations:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_participations", values[i])
			} else if value.Valid {
				_m.TotalParticipations = value.Int64
			}
		case activity.FieldTotalRewardsDistributed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_rewards_distributed", values[i])
			} else if value.Valid {
				_m.TotalRewardsDistributed = value.Int64
			}
		case activity.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case activity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case activity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Activity.
// This includes values selected through modifiers, order, etc.
func (_m *Activity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRewards queries the "rewards" edge of the Activity entity.
func (_m *Activity) QueryRewards() *ActivityRewardQuery {
	return NewActivityClient(_m.config).QueryRewards(_m)
}

// QueryParticipations queries the "participations" edge of the Activity entity.
func (_m *Activity) QueryParticipations() *ActivityParticipationQuery {
	return NewActivityClient(_m.config).QueryParticipations(_m)
}

// Update returns a builder for updating this Activity.
// Note that you need to call Activity.Unwrap() before calling this method if this Activity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Activity) Update() *ActivityUpdateOne {
	return NewActivityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Activity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Activity) Unwrap() *Activity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Activity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Activity) String() string {
	var builder strings.Builder
	builder.WriteString("Activity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	if v := _m.StartsAt; v != nil {
		builder.WriteString("starts_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndsAt; v != nil {
		builder.WriteString("ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("visibility_rules=")
	builder.WriteString(fmt.Sprintf("%v", _m.VisibilityRules))
	builder.WriteString(", ")
	builder.WriteString("participation_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParticipationConfig))
	builder.WriteString(", ")
	builder.WriteString("activity_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityConfig))
	builder.WriteString(", ")
	builder.WriteString("total_participations=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalParticipations))
	builder.WriteString(", ")
	builder.WriteString("total_rewards_distributed=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRewardsDistributed))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Activities is a parsable slice of Activity.
type Activities []*Activity
