// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ActivityRewardUpdate is the builder for updating ActivityReward entities.
type ActivityRewardUpdate struct {
	config
	hooks    []Hook
	mutation *ActivityRewardMutation
}

// Where appends a list predicates to the ActivityRewardUpdate builder.
func (_u *ActivityRewardUpdate) Where(ps ...predicate.ActivityReward) *ActivityRewardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *ActivityRewardUpdate) SetActivityID(v int64) *ActivityRewardUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableActivityID(v *int64) *ActivityRewardUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ActivityRewardUpdate) SetName(v string) *ActivityRewardUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableName(v *string) *ActivityRewardUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActivityRewardUpdate) SetDescription(v string) *ActivityRewardUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableDescription(v *string) *ActivityRewardUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ActivityRewardUpdate) SetIcon(v string) *ActivityRewardUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableIcon(v *string) *ActivityRewardUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *ActivityRewardUpdate) SetRewardType(v activityreward.RewardType) *ActivityRewardUpdate {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableRewardType(v *activityreward.RewardType) *ActivityRewardUpdate {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetRewardValue sets the "reward_value" field.
func (_u *ActivityRewardUpdate) SetRewardValue(v string) *ActivityRewardUpdate {
	_u.mutation.SetRewardValue(v)
	return _u
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableRewardValue(v *string) *ActivityRewardUpdate {
	if v != nil {
		_u.SetRewardValue(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ActivityRewardUpdate) SetWeight(v int) *ActivityRewardUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableWeight(v *int) *ActivityRewardUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ActivityRewardUpdate) AddWeight(v int) *ActivityRewardUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetProbability sets the "probability" field.
func (_u *ActivityRewardUpdate) SetProbability(v float64) *ActivityRewardUpdate {
	_u.mutation.ResetProbability()
	_u.mutation.SetProbability(v)
	return _u
}

// SetNillableProbability sets the "probability" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableProbability(v *float64) *ActivityRewardUpdate {
	if v != nil {
		_u.SetProbability(*v)
	}
	return _u
}

// AddProbability adds value to the "probability" field.
func (_u *ActivityRewardUpdate) AddProbability(v float64) *ActivityRewardUpdate {
	_u.mutation.AddProbability(v)
	return _u
}

// ClearProbability clears the value of the "probability" field.
func (_u *ActivityRewardUpdate) ClearProbability() *ActivityRewardUpdate {
	_u.mutation.ClearProbability()
	return _u
}

// SetTotalStock sets the "total_stock" field.
func (_u *ActivityRewardUpdate) SetTotalStock(v int64) *ActivityRewardUpdate {
	_u.mutation.ResetTotalStock()
	_u.mutation.SetTotalStock(v)
	return _u
}

// SetNillableTotalStock sets the "total_stock" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableTotalStock(v *int64) *ActivityRewardUpdate {
	if v != nil {
		_u.SetTotalStock(*v)
	}
	return _u
}

// AddTotalStock adds value to the "total_stock" field.
func (_u *ActivityRewardUpdate) AddTotalStock(v int64) *ActivityRewardUpdate {
	_u.mutation.AddTotalStock(v)
	return _u
}

// SetRemainingStock sets the "remaining_stock" field.
func (_u *ActivityRewardUpdate) SetRemainingStock(v int64) *ActivityRewardUpdate {
	_u.mutation.ResetRemainingStock()
	_u.mutation.SetRemainingStock(v)
	return _u
}

// SetNillableRemainingStock sets the "remaining_stock" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableRemainingStock(v *int64) *ActivityRewardUpdate {
	if v != nil {
		_u.SetRemainingStock(*v)
	}
	return _u
}

// AddRemainingStock adds value to the "remaining_stock" field.
func (_u *ActivityRewardUpdate) AddRemainingStock(v int64) *ActivityRewardUpdate {
	_u.mutation.AddRemainingStock(v)
	return _u
}

// SetTier sets the "tier" field.
func (_u *ActivityRewardUpdate) SetTier(v activityreward.Tier) *ActivityRewardUpdate {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableTier(v *activityreward.Tier) *ActivityRewardUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ActivityRewardUpdate) SetStatus(v activityreward.Status) *ActivityRewardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableStatus(v *activityreward.Status) *ActivityRewardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ActivityRewardUpdate) SetSortOrder(v int) *ActivityRewardUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableSortOrder(v *int) *ActivityRewardUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ActivityRewardUpdate) AddSortOrder(v int) *ActivityRewardUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDistributedCount sets the "distributed_count" field.
func (_u *ActivityRewardUpdate) SetDistributedCount(v int64) *ActivityRewardUpdate {
	_u.mutation.ResetDistributedCount()
	_u.mutation.SetDistributedCount(v)
	return _u
}

// SetNillableDistributedCount sets the "distributed_count" field if the given value is not nil.
func (_u *ActivityRewardUpdate) SetNillableDistributedCount(v *int64) *ActivityRewardUpdate {
	if v != nil {
		_u.SetDistributedCount(*v)
	}
	return _u
}

// AddDistributedCount adds value to the "distributed_count" field.
func (_u *ActivityRewardUpdate) AddDistributedCount(v int64) *ActivityRewardUpdate {
	_u.mutation.AddDistributedCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivityRewardUpdate) SetUpdatedAt(v time.Time) *ActivityRewardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActivity sets the "activity" edge to the Activity entity.
func (_u *ActivityRewardUpdate) SetActivity(v *Activity) *ActivityRewardUpdate {
	return _u.SetActivityID(v.ID)
}

// AddParticipationIDs adds the "participations" edge to the ActivityParticipation entity by IDs.
func (_u *ActivityRewardUpdate) AddParticipationIDs(ids ...int64) *ActivityRewardUpdate {
	_u.mutation.AddParticipationIDs(ids...)
	return _u
}

// AddParticipations adds the "participations" edges to the ActivityParticipation entity.
func (_u *ActivityRewardUpdate) AddParticipations(v ...*ActivityParticipation) *ActivityRewardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipationIDs(ids...)
}

// Mutation returns the ActivityRewardMutation object of the builder.
func (_u *ActivityRewardUpdate) Mutation() *ActivityRewardMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the Activity entity.
func (_u *ActivityRewardUpdate) ClearActivity() *ActivityRewardUpdate {
	_u.mutation.ClearActivity()
	return _u
}

// ClearParticipations clears all "participations" edges to the ActivityParticipation entity.
func (_u *ActivityRewardUpdate) ClearParticipations() *ActivityRewardUpdate {
	_u.mutation.ClearParticipations()
	return _u
}

// RemoveParticipationIDs removes the "participations" edge to ActivityParticipation entities by IDs.
func (_u *ActivityRewardUpdate) RemoveParticipationIDs(ids ...int64) *ActivityRewardUpdate {
	_u.mutation.RemoveParticipationIDs(ids...)
	return _u
}

// RemoveParticipations removes "participations" edges to ActivityParticipation entities.
func (_u *ActivityRewardUpdate) RemoveParticipations(v ...*ActivityParticipation) *ActivityRewardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivityRewardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityRewardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivityRewardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityRewardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivityRewardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := activityreward.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityRewardUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := activityreward.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RewardType(); ok {
		if err := activityreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tier(); ok {
		if err := activityreward.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := activityreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.status": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityReward.activity"`)
	}
	return nil
}

func (_u *ActivityRewardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activityreward.Table, activityreward.Columns, sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(activityreward.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(activityreward.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(activityreward.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(activityreward.FieldRewardType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RewardValue(); ok {
		_spec.SetField(activityreward.FieldRewardValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(activityreward.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(activityreward.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Probability(); ok {
		_spec.SetField(activityreward.FieldProbability, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProbability(); ok {
		_spec.AddField(activityreward.FieldProbability, field.TypeFloat64, value)
	}
	if _u.mutation.ProbabilityCleared() {
		_spec.ClearField(activityreward.FieldProbability, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalStock(); ok {
		_spec.SetField(activityreward.FieldTotalStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalStock(); ok {
		_spec.AddField(activityreward.FieldTotalStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RemainingStock(); ok {
		_spec.SetField(activityreward.FieldRemainingStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRemainingStock(); ok {
		_spec.AddField(activityreward.FieldRemainingStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(activityreward.FieldTier, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(activityreward.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(activityreward.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(activityreward.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DistributedCount(); ok {
		_spec.SetField(activityreward.FieldDistributedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDistributedCount(); ok {
		_spec.AddField(activityreward.FieldDistributedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activityreward.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityreward.ActivityTable,
			Columns: []string{activityreward.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityreward.ActivityTable,
			Columns: []string{activityreward.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activityreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivityRewardUpdateOne is the builder for updating a single ActivityReward entity.
type ActivityRewardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivityRewardMutation
}

// SetActivityID sets the "activity_id" field.
func (_u *ActivityRewardUpdateOne) SetActivityID(v int64) *ActivityRewardUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableActivityID(v *int64) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ActivityRewardUpdateOne) SetName(v string) *ActivityRewardUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableName(v *string) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActivityRewardUpdateOne) SetDescription(v string) *ActivityRewardUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableDescription(v *string) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ActivityRewardUpdateOne) SetIcon(v string) *ActivityRewardUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableIcon(v *string) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *ActivityRewardUpdateOne) SetRewardType(v activityreward.RewardType) *ActivityRewardUpdateOne {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableRewardType(v *activityreward.RewardType) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetRewardValue sets the "reward_value" field.
func (_u *ActivityRewardUpdateOne) SetRewardValue(v string) *ActivityRewardUpdateOne {
	_u.mutation.SetRewardValue(v)
	return _u
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableRewardValue(v *string) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetRewardValue(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ActivityRewardUpdateOne) SetWeight(v int) *ActivityRewardUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableWeight(v *int) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ActivityRewardUpdateOne) AddWeight(v int) *ActivityRewardUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetProbability sets the "probability" field.
func (_u *ActivityRewardUpdateOne) SetProbability(v float64) *ActivityRewardUpdateOne {
	_u.mutation.ResetProbability()
	_u.mutation.SetProbability(v)
	return _u
}

// SetNillableProbability sets the "probability" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableProbability(v *float64) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetProbability(*v)
	}
	return _u
}

// AddProbability adds value to the "probability" field.
func (_u *ActivityRewardUpdateOne) AddProbability(v float64) *ActivityRewardUpdateOne {
	_u.mutation.AddProbability(v)
	return _u
}

// ClearProbability clears the value of the "probability" field.
func (_u *ActivityRewardUpdateOne) ClearProbability() *ActivityRewardUpdateOne {
	_u.mutation.ClearProbability()
	return _u
}

// SetTotalStock sets the "total_stock" field.
func (_u *ActivityRewardUpdateOne) SetTotalStock(v int64) *ActivityRewardUpdateOne {
	_u.mutation.ResetTotalStock()
	_u.mutation.SetTotalStock(v)
	return _u
}

// SetNillableTotalStock sets the "total_stock" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableTotalStock(v *int64) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetTotalStock(*v)
	}
	return _u
}

// AddTotalStock adds value to the "total_stock" field.
func (_u *ActivityRewardUpdateOne) AddTotalStock(v int64) *ActivityRewardUpdateOne {
	_u.mutation.AddTotalStock(v)
	return _u
}

// SetRemainingStock sets the "remaining_stock" field.
func (_u *ActivityRewardUpdateOne) SetRemainingStock(v int64) *ActivityRewardUpdateOne {
	_u.mutation.ResetRemainingStock()
	_u.mutation.SetRemainingStock(v)
	return _u
}

// SetNillableRemainingStock sets the "remaining_stock" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableRemainingStock(v *int64) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetRemainingStock(*v)
	}
	return _u
}

// AddRemainingStock adds value to the "remaining_stock" field.
func (_u *ActivityRewardUpdateOne) AddRemainingStock(v int64) *ActivityRewardUpdateOne {
	_u.mutation.AddRemainingStock(v)
	return _u
}

// SetTier sets the "tier" field.
func (_u *ActivityRewardUpdateOne) SetTier(v activityreward.Tier) *ActivityRewardUpdateOne {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableTier(v *activityreward.Tier) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ActivityRewardUpdateOne) SetStatus(v activityreward.Status) *ActivityRewardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableStatus(v *activityreward.Status) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ActivityRewardUpdateOne) SetSortOrder(v int) *ActivityRewardUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableSortOrder(v *int) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ActivityRewardUpdateOne) AddSortOrder(v int) *ActivityRewardUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDistributedCount sets the "distributed_count" field.
func (_u *ActivityRewardUpdateOne) SetDistributedCount(v int64) *ActivityRewardUpdateOne {
	_u.mutation.ResetDistributedCount()
	_u.mutation.SetDistributedCount(v)
	return _u
}

// SetNillableDistributedCount sets the "distributed_count" field if the given value is not nil.
func (_u *ActivityRewardUpdateOne) SetNillableDistributedCount(v *int64) *ActivityRewardUpdateOne {
	if v != nil {
		_u.SetDistributedCount(*v)
	}
	return _u
}

// AddDistributedCount adds value to the "distributed_count" field.
func (_u *ActivityRewardUpdateOne) AddDistributedCount(v int64) *ActivityRewardUpdateOne {
	_u.mutation.AddDistributedCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivityRewardUpdateOne) SetUpdatedAt(v time.Time) *ActivityRewardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActivity sets the "activity" edge to the Activity entity.
func (_u *ActivityRewardUpdateOne) SetActivity(v *Activity) *ActivityRewardUpdateOne {
	return _u.SetActivityID(v.ID)
}

// AddParticipationIDs adds the "participations" edge to the ActivityParticipation entity by IDs.
func (_u *ActivityRewardUpdateOne) AddParticipationIDs(ids ...int64) *ActivityRewardUpdateOne {
	_u.mutation.AddParticipationIDs(ids...)
	return _u
}

// AddParticipations adds the "participations" edges to the ActivityParticipation entity.
func (_u *ActivityRewardUpdateOne) AddParticipations(v ...*ActivityParticipation) *ActivityRewardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipationIDs(ids...)
}

// Mutation returns the ActivityRewardMutation object of the builder.
func (_u *ActivityRewardUpdateOne) Mutation() *ActivityRewardMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the Activity entity.
func (_u *ActivityRewardUpdateOne) ClearActivity() *ActivityRewardUpdateOne {
	_u.mutation.ClearActivity()
	return _u
}

// ClearParticipations clears all "participations" edges to the ActivityParticipation entity.
func (_u *ActivityRewardUpdateOne) ClearParticipations() *ActivityRewardUpdateOne {
	_u.mutation.ClearParticipations()
	return _u
}

// RemoveParticipationIDs removes the "participations" edge to ActivityParticipation entities by IDs.
func (_u *ActivityRewardUpdateOne) RemoveParticipationIDs(ids ...int64) *ActivityRewardUpdateOne {
	_u.mutation.RemoveParticipationIDs(ids...)
	return _u
}

// RemoveParticipations removes "participations" edges to ActivityParticipation entities.
func (_u *ActivityRewardUpdateOne) RemoveParticipations(v ...*ActivityParticipation) *ActivityRewardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipationIDs(ids...)
}

// Where appends a list predicates to the ActivityRewardUpdate builder.
func (_u *ActivityRewardUpdateOne) Where(ps ...predicate.ActivityReward) *ActivityRewardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivityRewardUpdateOne) Select(field string, fields ...string) *ActivityRewardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActivityReward entity.
func (_u *ActivityRewardUpdateOne) Save(ctx context.Context) (*ActivityReward, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityRewardUpdateOne) SaveX(ctx context.Context) *ActivityReward {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivityRewardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityRewardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivityRewardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := activityreward.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityRewardUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := activityreward.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RewardType(); ok {
		if err := activityreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tier(); ok {
		if err := activityreward.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := activityreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.status": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityReward.activity"`)
	}
	return nil
}

func (_u *ActivityRewardUpdateOne) sqlSave(ctx context.Context) (_node *ActivityReward, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activityreward.Table, activityreward.Columns, sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActivityReward.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activityreward.FieldID)
		for _, f := range fields {
			if !activityreward.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activityreward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(activityreward.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(activityreward.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(activityreward.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(activityreward.FieldRewardType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RewardValue(); ok {
		_spec.SetField(activityreward.FieldRewardValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(activityreward.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(activityreward.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Probability(); ok {
		_spec.SetField(activityreward.FieldProbability, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProbability(); ok {
		_spec.AddField(activityreward.FieldProbability, field.TypeFloat64, value)
	}
	if _u.mutation.ProbabilityCleared() {
		_spec.ClearField(activityreward.FieldProbability, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalStock(); ok {
		_spec.SetField(activityreward.FieldTotalStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalStock(); ok {
		_spec.AddField(activityreward.FieldTotalStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RemainingStock(); ok {
		_spec.SetField(activityreward.FieldRemainingStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRemainingStock(); ok {
		_spec.AddField(activityreward.FieldRemainingStock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(activityreward.FieldTier, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(activityreward.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(activityreward.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(activityreward.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DistributedCount(); ok {
		_spec.SetField(activityreward.FieldDistributedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDistributedCount(); ok {
		_spec.AddField(activityreward.FieldDistributedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activityreward.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityreward.ActivityTable,
			Columns: []string{activityreward.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityreward.ActivityTable,
			Columns: []string{activityreward.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActivityReward{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activityreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
