// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ActivityParticipationCreate is the builder for creating a ActivityParticipation entity.
type ActivityParticipationCreate struct {
	config
	mutation *ActivityParticipationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityID sets the "activity_id" field.
func (_c *ActivityParticipationCreate) SetActivityID(v int64) *ActivityParticipationCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ActivityParticipationCreate) SetUserID(v int64) *ActivityParticipationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetParticipatedAt sets the "participated_at" field.
func (_c *ActivityParticipationCreate) SetParticipatedAt(v time.Time) *ActivityParticipationCreate {
	_c.mutation.SetParticipatedAt(v)
	return _c
}

// SetNillableParticipatedAt sets the "participated_at" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableParticipatedAt(v *time.Time) *ActivityParticipationCreate {
	if v != nil {
		_c.SetParticipatedAt(*v)
	}
	return _c
}

// SetDailyWindow sets the "daily_window" field.
func (_c *ActivityParticipationCreate) SetDailyWindow(v time.Time) *ActivityParticipationCreate {
	_c.mutation.SetDailyWindow(v)
	return _c
}

// SetWeeklyWindow sets the "weekly_window" field.
func (_c *ActivityParticipationCreate) SetWeeklyWindow(v time.Time) *ActivityParticipationCreate {
	_c.mutation.SetWeeklyWindow(v)
	return _c
}

// SetMonthlyWindow sets the "monthly_window" field.
func (_c *ActivityParticipationCreate) SetMonthlyWindow(v time.Time) *ActivityParticipationCreate {
	_c.mutation.SetMonthlyWindow(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *ActivityParticipationCreate) SetResult(v activityparticipation.Result) *ActivityParticipationCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableResult(v *activityparticipation.Result) *ActivityParticipationCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetRewardsReceived sets the "rewards_received" field.
func (_c *ActivityParticipationCreate) SetRewardsReceived(v []map[string]interface{}) *ActivityParticipationCreate {
	_c.mutation.SetRewardsReceived(v)
	return _c
}

// SetRewardID sets the "reward_id" field.
func (_c *ActivityParticipationCreate) SetRewardID(v int64) *ActivityParticipationCreate {
	_c.mutation.SetRewardID(v)
	return _c
}

// SetNillableRewardID sets the "reward_id" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableRewardID(v *int64) *ActivityParticipationCreate {
	if v != nil {
		_c.SetRewardID(*v)
	}
	return _c
}

// SetCostBalance sets the "cost_balance" field.
func (_c *ActivityParticipationCreate) SetCostBalance(v string) *ActivityParticipationCreate {
	_c.mutation.SetCostBalance(v)
	return _c
}

// SetNillableCostBalance sets the "cost_balance" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableCostBalance(v *string) *ActivityParticipationCreate {
	if v != nil {
		_c.SetCostBalance(*v)
	}
	return _c
}

// SetExtraData sets the "extra_data" field.
func (_c *ActivityParticipationCreate) SetExtraData(v map[string]interface{}) *ActivityParticipationCreate {
	_c.mutation.SetExtraData(v)
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *ActivityParticipationCreate) SetIPAddress(v string) *ActivityParticipationCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableIPAddress(v *string) *ActivityParticipationCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *ActivityParticipationCreate) SetUserAgent(v string) *ActivityParticipationCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableUserAgent(v *string) *ActivityParticipationCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivityParticipationCreate) SetCreatedAt(v time.Time) *ActivityParticipationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivityParticipationCreate) SetNillableCreatedAt(v *time.Time) *ActivityParticipationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ActivityParticipationCreate) SetID(v int64) *ActivityParticipationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetActivity sets the "activity" edge to the Activity entity.
func (_c *ActivityParticipationCreate) SetActivity(v *Activity) *ActivityParticipationCreate {
	return _c.SetActivityID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ActivityParticipationCreate) SetUser(v *User) *ActivityParticipationCreate {
	return _c.SetUserID(v.ID)
}

// SetReward sets the "reward" edge to the ActivityReward entity.
func (_c *ActivityParticipationCreate) SetReward(v *ActivityReward) *ActivityParticipationCreate {
	return _c.SetRewardID(v.ID)
}

// Mutation returns the ActivityParticipationMutation object of the builder.
func (_c *ActivityParticipationCreate) Mutation() *ActivityParticipationMutation {
	return _c.mutation
}

// Save creates the ActivityParticipation in the database.
func (_c *ActivityParticipationCreate) Save(ctx context.Context) (*ActivityParticipation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivityParticipationCreate) SaveX(ctx context.Context) *ActivityParticipation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityParticipationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityParticipationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivityParticipationCreate) defaults() {
	if _, ok := _c.mutation.ParticipatedAt(); !ok {
		v := activityparticipation.DefaultParticipatedAt()
		_c.mutation.SetParticipatedAt(v)
	}
	if _, ok := _c.mutation.Result(); !ok {
		v := activityparticipation.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.CostBalance(); !ok {
		v := activityparticipation.DefaultCostBalance
		_c.mutation.SetCostBalance(v)
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		v := activityparticipation.DefaultIPAddress
		_c.mutation.SetIPAddress(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := activityparticipation.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activityparticipation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivityParticipationCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "ActivityParticipation.activity_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ActivityParticipation.user_id"`)}
	}
	if _, ok := _c.mutation.ParticipatedAt(); !ok {
		return &ValidationError{Name: "participated_at", err: errors.New(`ent: missing required field "ActivityParticipation.participated_at"`)}
	}
	if _, ok := _c.mutation.DailyWindow(); !ok {
		return &ValidationError{Name: "daily_window", err: errors.New(`ent: missing required field "ActivityParticipation.daily_window"`)}
	}
	if _, ok := _c.mutation.WeeklyWindow(); !ok {
		return &ValidationError{Name: "weekly_window", err: errors.New(`ent: missing required field "ActivityParticipation.weekly_window"`)}
	}
	if _, ok := _c.mutation.MonthlyWindow(); !ok {
		return &ValidationError{Name: "monthly_window", err: errors.New(`ent: missing required field "ActivityParticipation.monthly_window"`)}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "ActivityParticipation.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := activityparticipation.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ActivityParticipation.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostBalance(); !ok {
		return &ValidationError{Name: "cost_balance", err: errors.New(`ent: missing required field "ActivityParticipation.cost_balance"`)}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "ActivityParticipation.ip_address"`)}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "ActivityParticipation.user_agent"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivityParticipation.created_at"`)}
	}
	if len(_c.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "ActivityParticipation.activity"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ActivityParticipation.user"`)}
	}
	return nil
}

func (_c *ActivityParticipationCreate) sqlSave(ctx context.Context) (*ActivityParticipation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivityParticipationCreate) createSpec() (*ActivityParticipation, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityParticipation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activityparticipation.Table, sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ParticipatedAt(); ok {
		_spec.SetField(activityparticipation.FieldParticipatedAt, field.TypeTime, value)
		_node.ParticipatedAt = value
	}
	if value, ok := _c.mutation.DailyWindow(); ok {
		_spec.SetField(activityparticipation.FieldDailyWindow, field.TypeTime, value)
		_node.DailyWindow = value
	}
	if value, ok := _c.mutation.WeeklyWindow(); ok {
		_spec.SetField(activityparticipation.FieldWeeklyWindow, field.TypeTime, value)
		_node.WeeklyWindow = value
	}
	if value, ok := _c.mutation.MonthlyWindow(); ok {
		_spec.SetField(activityparticipation.FieldMonthlyWindow, field.TypeTime, value)
		_node.MonthlyWindow = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(activityparticipation.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.RewardsReceived(); ok {
		_spec.SetField(activityparticipation.FieldRewardsReceived, field.TypeJSON, value)
		_node.RewardsReceived = value
	}
	if value, ok := _c.mutation.CostBalance(); ok {
		_spec.SetField(activityparticipation.FieldCostBalance, field.TypeString, value)
		_node.CostBalance = value
	}
	if value, ok := _c.mutation.ExtraData(); ok {
		_spec.SetField(activityparticipation.FieldExtraData, field.TypeJSON, value)
		_node.ExtraData = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(activityparticipation.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(activityparticipation.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activityparticipation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.ActivityTable,
			Columns: []string{activityparticipation.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.UserTable,
			Columns: []string{activityparticipation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RewardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.RewardTable,
			Columns: []string{activityparticipation.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RewardID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityParticipation.Create().
//		SetActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityParticipationUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityParticipationCreate) OnConflict(opts ...sql.ConflictOption) *ActivityParticipationUpsertOne {
	_c.conflict = opts
	return &ActivityParticipationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityParticipation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityParticipationCreate) OnConflictColumns(columns ...string) *ActivityParticipationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityParticipationUpsertOne{
		create: _c,
	}
}

type (
	// ActivityParticipationUpsertOne is the builder for "upsert"-ing
	//  one ActivityParticipation node.
	ActivityParticipationUpsertOne struct {
		create *ActivityParticipationCreate
	}

	// ActivityParticipationUpsert is the "OnConflict" setter.
	ActivityParticipationUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityID sets the "activity_id" field.
func (u *ActivityParticipationUpsert) SetActivityID(v int64) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateActivityID() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldActivityID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ActivityParticipationUpsert) SetUserID(v int64) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateUserID() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldUserID)
	return u
}

// SetParticipatedAt sets the "participated_at" field.
func (u *ActivityParticipationUpsert) SetParticipatedAt(v time.Time) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldParticipatedAt, v)
	return u
}

// UpdateParticipatedAt sets the "participated_at" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateParticipatedAt() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldParticipatedAt)
	return u
}

// SetDailyWindow sets the "daily_window" field.
func (u *ActivityParticipationUpsert) SetDailyWindow(v time.Time) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldDailyWindow, v)
	return u
}

// UpdateDailyWindow sets the "daily_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateDailyWindow() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldDailyWindow)
	return u
}

// SetWeeklyWindow sets the "weekly_window" field.
func (u *ActivityParticipationUpsert) SetWeeklyWindow(v time.Time) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldWeeklyWindow, v)
	return u
}

// UpdateWeeklyWindow sets the "weekly_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateWeeklyWindow() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldWeeklyWindow)
	return u
}

// SetMonthlyWindow sets the "monthly_window" field.
func (u *ActivityParticipationUpsert) SetMonthlyWindow(v time.Time) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldMonthlyWindow, v)
	return u
}

// UpdateMonthlyWindow sets the "monthly_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateMonthlyWindow() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldMonthlyWindow)
	return u
}

// SetResult sets the "result" field.
func (u *ActivityParticipationUpsert) SetResult(v activityparticipation.Result) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateResult() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldResult)
	return u
}

// SetRewardsReceived sets the "rewards_received" field.
func (u *ActivityParticipationUpsert) SetRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldRewardsReceived, v)
	return u
}

// UpdateRewardsReceived sets the "rewards_received" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateRewardsReceived() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldRewardsReceived)
	return u
}

// ClearRewardsReceived clears the value of the "rewards_received" field.
func (u *ActivityParticipationUpsert) ClearRewardsReceived() *ActivityParticipationUpsert {
	u.SetNull(activityparticipation.FieldRewardsReceived)
	return u
}

// SetRewardID sets the "reward_id" field.
func (u *ActivityParticipationUpsert) SetRewardID(v int64) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldRewardID, v)
	return u
}

// UpdateRewardID sets the "reward_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateRewardID() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldRewardID)
	return u
}

// ClearRewardID clears the value of the "reward_id" field.
func (u *ActivityParticipationUpsert) ClearRewardID() *ActivityParticipationUpsert {
	u.SetNull(activityparticipation.FieldRewardID)
	return u
}

// SetCostBalance sets the "cost_balance" field.
func (u *ActivityParticipationUpsert) SetCostBalance(v string) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldCostBalance, v)
	return u
}

// UpdateCostBalance sets the "cost_balance" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateCostBalance() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldCostBalance)
	return u
}

// SetExtraData sets the "extra_data" field.
func (u *ActivityParticipationUpsert) SetExtraData(v map[string]interface{}) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldExtraData, v)
	return u
}

// UpdateExtraData sets the "extra_data" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateExtraData() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldExtraData)
	return u
}

// ClearExtraData clears the value of the "extra_data" field.
func (u *ActivityParticipationUpsert) ClearExtraData() *ActivityParticipationUpsert {
	u.SetNull(activityparticipation.FieldExtraData)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *ActivityParticipationUpsert) SetIPAddress(v string) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateIPAddress() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldIPAddress)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *ActivityParticipationUpsert) SetUserAgent(v string) *ActivityParticipationUpsert {
	u.Set(activityparticipation.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *ActivityParticipationUpsert) UpdateUserAgent() *ActivityParticipationUpsert {
	u.SetExcluded(activityparticipation.FieldUserAgent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ActivityParticipation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(activityparticipation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ActivityParticipationUpsertOne) UpdateNewValues() *ActivityParticipationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(activityparticipation.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(activityparticipation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityParticipation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ActivityParticipationUpsertOne) Ignore() *ActivityParticipationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityParticipationUpsertOne) DoNothing() *ActivityParticipationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityParticipationCreate.OnConflict
// documentation for more info.
func (u *ActivityParticipationUpsertOne) Update(set func(*ActivityParticipationUpsert)) *ActivityParticipationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityParticipationUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *ActivityParticipationUpsertOne) SetActivityID(v int64) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateActivityID() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateActivityID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ActivityParticipationUpsertOne) SetUserID(v int64) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateUserID() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateUserID()
	})
}

// SetParticipatedAt sets the "participated_at" field.
func (u *ActivityParticipationUpsertOne) SetParticipatedAt(v time.Time) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetParticipatedAt(v)
	})
}

// UpdateParticipatedAt sets the "participated_at" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateParticipatedAt() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateParticipatedAt()
	})
}

// SetDailyWindow sets the "daily_window" field.
func (u *ActivityParticipationUpsertOne) SetDailyWindow(v time.Time) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetDailyWindow(v)
	})
}

// UpdateDailyWindow sets the "daily_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateDailyWindow() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateDailyWindow()
	})
}

// SetWeeklyWindow sets the "weekly_window" field.
func (u *ActivityParticipationUpsertOne) SetWeeklyWindow(v time.Time) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetWeeklyWindow(v)
	})
}

// UpdateWeeklyWindow sets the "weekly_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateWeeklyWindow() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateWeeklyWindow()
	})
}

// SetMonthlyWindow sets the "monthly_window" field.
func (u *ActivityParticipationUpsertOne) SetMonthlyWindow(v time.Time) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetMonthlyWindow(v)
	})
}

// UpdateMonthlyWindow sets the "monthly_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateMonthlyWindow() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateMonthlyWindow()
	})
}

// SetResult sets the "result" field.
func (u *ActivityParticipationUpsertOne) SetResult(v activityparticipation.Result) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateResult() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateResult()
	})
}

// SetRewardsReceived sets the "rewards_received" field.
func (u *ActivityParticipationUpsertOne) SetRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetRewardsReceived(v)
	})
}

// UpdateRewardsReceived sets the "rewards_received" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateRewardsReceived() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateRewardsReceived()
	})
}

// ClearRewardsReceived clears the value of the "rewards_received" field.
func (u *ActivityParticipationUpsertOne) ClearRewardsReceived() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.ClearRewardsReceived()
	})
}

// SetRewardID sets the "reward_id" field.
func (u *ActivityParticipationUpsertOne) SetRewardID(v int64) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetRewardID(v)
	})
}

// UpdateRewardID sets the "reward_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateRewardID() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateRewardID()
	})
}

// ClearRewardID clears the value of the "reward_id" field.
func (u *ActivityParticipationUpsertOne) ClearRewardID() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.ClearRewardID()
	})
}

// SetCostBalance sets the "cost_balance" field.
func (u *ActivityParticipationUpsertOne) SetCostBalance(v string) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetCostBalance(v)
	})
}

// UpdateCostBalance sets the "cost_balance" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateCostBalance() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateCostBalance()
	})
}

// SetExtraData sets the "extra_data" field.
func (u *ActivityParticipationUpsertOne) SetExtraData(v map[string]interface{}) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetExtraData(v)
	})
}

// UpdateExtraData sets the "extra_data" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateExtraData() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateExtraData()
	})
}

// ClearExtraData clears the value of the "extra_data" field.
func (u *ActivityParticipationUpsertOne) ClearExtraData() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.ClearExtraData()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *ActivityParticipationUpsertOne) SetIPAddress(v string) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateIPAddress() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *ActivityParticipationUpsertOne) SetUserAgent(v string) *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *ActivityParticipationUpsertOne) UpdateUserAgent() *ActivityParticipationUpsertOne {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateUserAgent()
	})
}

// Exec executes the query.
func (u *ActivityParticipationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityParticipationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityParticipationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ActivityParticipationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ActivityParticipationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ActivityParticipationCreateBulk is the builder for creating many ActivityParticipation entities in bulk.
type ActivityParticipationCreateBulk struct {
	config
	err      error
	builders []*ActivityParticipationCreate
	conflict []sql.ConflictOption
}

// Save creates the ActivityParticipation entities in the database.
func (_c *ActivityParticipationCreateBulk) Save(ctx context.Context) ([]*ActivityParticipation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActivityParticipation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityParticipationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivityParticipationCreateBulk) SaveX(ctx context.Context) []*ActivityParticipation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityParticipationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityParticipationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityParticipation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityParticipationUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityParticipationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ActivityParticipationUpsertBulk {
	_c.conflict = opts
	return &ActivityParticipationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityParticipation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityParticipationCreateBulk) OnConflictColumns(columns ...string) *ActivityParticipationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityParticipationUpsertBulk{
		create: _c,
	}
}

// ActivityParticipationUpsertBulk is the builder for "upsert"-ing
// a bulk of ActivityParticipation nodes.
type ActivityParticipationUpsertBulk struct {
	create *ActivityParticipationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ActivityParticipation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(activityparticipation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ActivityParticipationUpsertBulk) UpdateNewValues() *ActivityParticipationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(activityparticipation.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(activityparticipation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityParticipation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ActivityParticipationUpsertBulk) Ignore() *ActivityParticipationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityParticipationUpsertBulk) DoNothing() *ActivityParticipationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityParticipationCreateBulk.OnConflict
// documentation for more info.
func (u *ActivityParticipationUpsertBulk) Update(set func(*ActivityParticipationUpsert)) *ActivityParticipationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityParticipationUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *ActivityParticipationUpsertBulk) SetActivityID(v int64) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateActivityID() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateActivityID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ActivityParticipationUpsertBulk) SetUserID(v int64) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateUserID() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateUserID()
	})
}

// SetParticipatedAt sets the "participated_at" field.
func (u *ActivityParticipationUpsertBulk) SetParticipatedAt(v time.Time) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetParticipatedAt(v)
	})
}

// UpdateParticipatedAt sets the "participated_at" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateParticipatedAt() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateParticipatedAt()
	})
}

// SetDailyWindow sets the "daily_window" field.
func (u *ActivityParticipationUpsertBulk) SetDailyWindow(v time.Time) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetDailyWindow(v)
	})
}

// UpdateDailyWindow sets the "daily_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateDailyWindow() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateDailyWindow()
	})
}

// SetWeeklyWindow sets the "weekly_window" field.
func (u *ActivityParticipationUpsertBulk) SetWeeklyWindow(v time.Time) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetWeeklyWindow(v)
	})
}

// UpdateWeeklyWindow sets the "weekly_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateWeeklyWindow() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateWeeklyWindow()
	})
}

// SetMonthlyWindow sets the "monthly_window" field.
func (u *ActivityParticipationUpsertBulk) SetMonthlyWindow(v time.Time) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetMonthlyWindow(v)
	})
}

// UpdateMonthlyWindow sets the "monthly_window" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateMonthlyWindow() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateMonthlyWindow()
	})
}

// SetResult sets the "result" field.
func (u *ActivityParticipationUpsertBulk) SetResult(v activityparticipation.Result) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateResult() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateResult()
	})
}

// SetRewardsReceived sets the "rewards_received" field.
func (u *ActivityParticipationUpsertBulk) SetRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetRewardsReceived(v)
	})
}

// UpdateRewardsReceived sets the "rewards_received" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateRewardsReceived() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateRewardsReceived()
	})
}

// ClearRewardsReceived clears the value of the "rewards_received" field.
func (u *ActivityParticipationUpsertBulk) ClearRewardsReceived() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.ClearRewardsReceived()
	})
}

// SetRewardID sets the "reward_id" field.
func (u *ActivityParticipationUpsertBulk) SetRewardID(v int64) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetRewardID(v)
	})
}

// UpdateRewardID sets the "reward_id" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateRewardID() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateRewardID()
	})
}

// ClearRewardID clears the value of the "reward_id" field.
func (u *ActivityParticipationUpsertBulk) ClearRewardID() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.ClearRewardID()
	})
}

// SetCostBalance sets the "cost_balance" field.
func (u *ActivityParticipationUpsertBulk) SetCostBalance(v string) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetCostBalance(v)
	})
}

// UpdateCostBalance sets the "cost_balance" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateCostBalance() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateCostBalance()
	})
}

// SetExtraData sets the "extra_data" field.
func (u *ActivityParticipationUpsertBulk) SetExtraData(v map[string]interface{}) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetExtraData(v)
	})
}

// UpdateExtraData sets the "extra_data" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateExtraData() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateExtraData()
	})
}

// ClearExtraData clears the value of the "extra_data" field.
func (u *ActivityParticipationUpsertBulk) ClearExtraData() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.ClearExtraData()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *ActivityParticipationUpsertBulk) SetIPAddress(v string) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateIPAddress() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *ActivityParticipationUpsertBulk) SetUserAgent(v string) *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *ActivityParticipationUpsertBulk) UpdateUserAgent() *ActivityParticipationUpsertBulk {
	return u.Update(func(s *ActivityParticipationUpsert) {
		s.UpdateUserAgent()
	})
}

// Exec executes the query.
func (u *ActivityParticipationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ActivityParticipationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityParticipationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityParticipationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
