// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
)

// ActivityReward is the model entity for the ActivityReward schema.
type ActivityReward struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 关联的活动ID
	ActivityID int64 `json:"activity_id,omitempty"`
	// 奖励名称，如'5元余额'、'7天订阅'
	Name string `json:"name,omitempty"`
	// 奖励描述
	Description string `json:"description,omitempty"`
	// 奖励图标
	Icon string `json:"icon,omitempty"`
	// 奖励类型: balance=余额, subscription=订阅, coupon=优惠券, points=积分, custom=自定义
	RewardType activityreward.RewardType `json:"reward_type,omitempty"`
	// 奖励值，JSON格式 {amount:10.5} 或 {group_id:1,days:7}
	RewardValue string `json:"reward_value,omitempty"`
	// 抽奖权重，越大概率越高（仅抽奖活动使用）
	Weight int `json:"weight,omitempty"`
	// 概率百分比（0-100），用于显示，可选
	Probability float64 `json:"probability,omitempty"`
	// 总库存，0表示无限
	TotalStock int64 `json:"total_stock,omitempty"`
	// 剩余库存
	RemainingStock int64 `json:"remaining_stock,omitempty"`
	// 奖励等级: grand=特等奖, first=一等奖, second=二等奖, third=三等奖, common=普通奖, consolation=安慰奖
	Tier activityreward.Tier `json:"tier,omitempty"`
	// 奖励状态
	Status activityreward.Status `json:"status,omitempty"`
	// 显示排序
	SortOrder int `json:"sort_order,omitempty"`
	// 已发放次数
	DistributedCount int64 `json:"distributed_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityRewardQuery when eager-loading is set.
	Edges        ActivityRewardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActivityRewardEdges holds the relations/edges for other nodes in the graph.
type ActivityRewardEdges struct {
	// Activity holds the value of the activity edge.
	Activity *Activity `json:"activity,omitempty"`
	// Participations holds the value of the participations edge.
	Participations []*ActivityParticipation `json:"participations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ActivityOrErr returns the Activity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityRewardEdges) ActivityOrErr() (*Activity, error) {
	if e.Activity != nil {
		return e.Activity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: activity.Label}
	}
	return nil, &NotLoadedError{edge: "activity"}
}

// ParticipationsOrErr returns the Participations value or an error if the edge
// was not loaded in eager-loading.
func (e ActivityRewardEdges) ParticipationsOrErr() ([]*ActivityParticipation, error) {
	if e.loadedTypes[1] {
		return e.Participations, nil
	}
	return nil, &NotLoadedError{edge: "participations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActivityReward) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activityreward.FieldProbability:
			values[i] = new(sql.NullFloat64)
		case activityreward.FieldID, activityreward.FieldActivityID, activityreward.FieldWeight, activityreward.FieldTotalStock, activityreward.FieldRemainingStock, activityreward.FieldSortOrder, activityreward.FieldDistributedCount:
			values[i] = new(sql.NullInt64)
		case activityreward.FieldName, activityreward.FieldDescription, activityreward.FieldIcon, activityreward.FieldRewardType, activityreward.FieldRewardValue, activityreward.FieldTier, activityreward.FieldStatus:
			values[i] = new(sql.NullString)
		case activityreward.FieldCreatedAt, activityreward.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActivityReward fields.
func (_m *ActivityReward) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activityreward.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case activityreward.FieldActivityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = value.Int64
			}
		case activityreward.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case activityreward.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case activityreward.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case activityreward.FieldRewardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_type", values[i])
			} else if value.Valid {
				_m.RewardType = activityreward.RewardType(value.String)
			}
		case activityreward.FieldRewardValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_value", values[i])
			} else if value.Valid {
				_m.RewardValue = value.String
			}
		case activityreward.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case activityreward.FieldProbability:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field probability", values[i])
			} else if value.Valid {
				_m.Probability = value.Float64
			}
		case activityreward.FieldTotalStock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_stock", values[i])
			} else if value.Valid {
				_m.TotalStock = value.Int64
			}
		case activityreward.FieldRemainingStock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_stock", values[i])
			} else if value.Valid {
				_m.RemainingStock = value.Int64
			}
		case activityreward.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = activityreward.Tier(value.String)
			}
		case activityreward.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = activityreward.Status(value.String)
			}
		case activityreward.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case activityreward.FieldDistributedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field distributed_count", values[i])
			} else if value.Valid {
				_m.DistributedCount = value.Int64
			}
		case activityreward.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case activityreward.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActivityReward.
// This includes values selected through modifiers, order, etc.
func (_m *ActivityReward) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActivity queries the "activity" edge of the ActivityReward entity.
func (_m *ActivityReward) QueryActivity() *ActivityQuery {
	return NewActivityRewardClient(_m.config).QueryActivity(_m)
}

// QueryParticipations queries the "participations" edge of the ActivityReward entity.
func (_m *ActivityReward) QueryParticipations() *ActivityParticipationQuery {
	return NewActivityRewardClient(_m.config).QueryParticipations(_m)
}

// Update returns a builder for updating this ActivityReward.
// Note that you need to call ActivityReward.Unwrap() before calling this method if this ActivityReward
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActivityReward) Update() *ActivityRewardUpdateOne {
	return NewActivityRewardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActivityReward entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActivityReward) Unwrap() *ActivityReward {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActivityReward is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActivityReward) String() string {
	var builder strings.Builder
	builder.WriteString("ActivityReward(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("activity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("reward_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardType))
	builder.WriteString(", ")
	builder.WriteString("reward_value=")
	builder.WriteString(_m.RewardValue)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("probability=")
	builder.WriteString(fmt.Sprintf("%v", _m.Probability))
	builder.WriteString(", ")
	builder.WriteString("total_stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalStock))
	builder.WriteString(", ")
	builder.WriteString("remaining_stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemainingStock))
	builder.WriteString(", ")
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tier))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("distributed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DistributedCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ActivityRewards is a parsable slice of ActivityReward.
type ActivityRewards []*ActivityReward
