// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ActivityParticipationUpdate is the builder for updating ActivityParticipation entities.
type ActivityParticipationUpdate struct {
	config
	hooks    []Hook
	mutation *ActivityParticipationMutation
}

// Where appends a list predicates to the ActivityParticipationUpdate builder.
func (_u *ActivityParticipationUpdate) Where(ps ...predicate.ActivityParticipation) *ActivityParticipationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *ActivityParticipationUpdate) SetActivityID(v int64) *ActivityParticipationUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableActivityID(v *int64) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ActivityParticipationUpdate) SetUserID(v int64) *ActivityParticipationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableUserID(v *int64) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParticipatedAt sets the "participated_at" field.
func (_u *ActivityParticipationUpdate) SetParticipatedAt(v time.Time) *ActivityParticipationUpdate {
	_u.mutation.SetParticipatedAt(v)
	return _u
}

// SetNillableParticipatedAt sets the "participated_at" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableParticipatedAt(v *time.Time) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetParticipatedAt(*v)
	}
	return _u
}

// SetDailyWindow sets the "daily_window" field.
func (_u *ActivityParticipationUpdate) SetDailyWindow(v time.Time) *ActivityParticipationUpdate {
	_u.mutation.SetDailyWindow(v)
	return _u
}

// SetNillableDailyWindow sets the "daily_window" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableDailyWindow(v *time.Time) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetDailyWindow(*v)
	}
	return _u
}

// SetWeeklyWindow sets the "weekly_window" field.
func (_u *ActivityParticipationUpdate) SetWeeklyWindow(v time.Time) *ActivityParticipationUpdate {
	_u.mutation.SetWeeklyWindow(v)
	return _u
}

// SetNillableWeeklyWindow sets the "weekly_window" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableWeeklyWindow(v *time.Time) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetWeeklyWindow(*v)
	}
	return _u
}

// SetMonthlyWindow sets the "monthly_window" field.
func (_u *ActivityParticipationUpdate) SetMonthlyWindow(v time.Time) *ActivityParticipationUpdate {
	_u.mutation.SetMonthlyWindow(v)
	return _u
}

// SetNillableMonthlyWindow sets the "monthly_window" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableMonthlyWindow(v *time.Time) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetMonthlyWindow(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ActivityParticipationUpdate) SetResult(v activityparticipation.Result) *ActivityParticipationUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableResult(v *activityparticipation.Result) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetRewardsReceived sets the "rewards_received" field.
func (_u *ActivityParticipationUpdate) SetRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpdate {
	_u.mutation.SetRewardsReceived(v)
	return _u
}

// AppendRewardsReceived appends value to the "rewards_received" field.
func (_u *ActivityParticipationUpdate) AppendRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpdate {
	_u.mutation.AppendRewardsReceived(v)
	return _u
}

// ClearRewardsReceived clears the value of the "rewards_received" field.
func (_u *ActivityParticipationUpdate) ClearRewardsReceived() *ActivityParticipationUpdate {
	_u.mutation.ClearRewardsReceived()
	return _u
}

// SetRewardID sets the "reward_id" field.
func (_u *ActivityParticipationUpdate) SetRewardID(v int64) *ActivityParticipationUpdate {
	_u.mutation.SetRewardID(v)
	return _u
}

// SetNillableRewardID sets the "reward_id" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableRewardID(v *int64) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetRewardID(*v)
	}
	return _u
}

// ClearRewardID clears the value of the "reward_id" field.
func (_u *ActivityParticipationUpdate) ClearRewardID() *ActivityParticipationUpdate {
	_u.mutation.ClearRewardID()
	return _u
}

// SetCostBalance sets the "cost_balance" field.
func (_u *ActivityParticipationUpdate) SetCostBalance(v string) *ActivityParticipationUpdate {
	_u.mutation.SetCostBalance(v)
	return _u
}

// SetNillableCostBalance sets the "cost_balance" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableCostBalance(v *string) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetCostBalance(*v)
	}
	return _u
}

// SetExtraData sets the "extra_data" field.
func (_u *ActivityParticipationUpdate) SetExtraData(v map[string]interface{}) *ActivityParticipationUpdate {
	_u.mutation.SetExtraData(v)
	return _u
}

// ClearExtraData clears the value of the "extra_data" field.
func (_u *ActivityParticipationUpdate) ClearExtraData() *ActivityParticipationUpdate {
	_u.mutation.ClearExtraData()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ActivityParticipationUpdate) SetIPAddress(v string) *ActivityParticipationUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableIPAddress(v *string) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ActivityParticipationUpdate) SetUserAgent(v string) *ActivityParticipationUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ActivityParticipationUpdate) SetNillableUserAgent(v *string) *ActivityParticipationUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetActivity sets the "activity" edge to the Activity entity.
func (_u *ActivityParticipationUpdate) SetActivity(v *Activity) *ActivityParticipationUpdate {
	return _u.SetActivityID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ActivityParticipationUpdate) SetUser(v *User) *ActivityParticipationUpdate {
	return _u.SetUserID(v.ID)
}

// SetReward sets the "reward" edge to the ActivityReward entity.
func (_u *ActivityParticipationUpdate) SetReward(v *ActivityReward) *ActivityParticipationUpdate {
	return _u.SetRewardID(v.ID)
}

// Mutation returns the ActivityParticipationMutation object of the builder.
func (_u *ActivityParticipationUpdate) Mutation() *ActivityParticipationMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the Activity entity.
func (_u *ActivityParticipationUpdate) ClearActivity() *ActivityParticipationUpdate {
	_u.mutation.ClearActivity()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ActivityParticipationUpdate) ClearUser() *ActivityParticipationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearReward clears the "reward" edge to the ActivityReward entity.
func (_u *ActivityParticipationUpdate) ClearReward() *ActivityParticipationUpdate {
	_u.mutation.ClearReward()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivityParticipationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityParticipationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivityParticipationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityParticipationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityParticipationUpdate) check() error {
	if v, ok := _u.mutation.Result(); ok {
		if err := activityparticipation.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ActivityParticipation.result": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityParticipation.activity"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityParticipation.user"`)
	}
	return nil
}

func (_u *ActivityParticipationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activityparticipation.Table, activityparticipation.Columns, sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParticipatedAt(); ok {
		_spec.SetField(activityparticipation.FieldParticipatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyWindow(); ok {
		_spec.SetField(activityparticipation.FieldDailyWindow, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WeeklyWindow(); ok {
		_spec.SetField(activityparticipation.FieldWeeklyWindow, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MonthlyWindow(); ok {
		_spec.SetField(activityparticipation.FieldMonthlyWindow, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(activityparticipation.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RewardsReceived(); ok {
		_spec.SetField(activityparticipation.FieldRewardsReceived, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRewardsReceived(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, activityparticipation.FieldRewardsReceived, value)
		})
	}
	if _u.mutation.RewardsReceivedCleared() {
		_spec.ClearField(activityparticipation.FieldRewardsReceived, field.TypeJSON)
	}
	if value, ok := _u.mutation.CostBalance(); ok {
		_spec.SetField(activityparticipation.FieldCostBalance, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtraData(); ok {
		_spec.SetField(activityparticipation.FieldExtraData, field.TypeJSON, value)
	}
	if _u.mutation.ExtraDataCleared() {
		_spec.ClearField(activityparticipation.FieldExtraData, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(activityparticipation.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(activityparticipation.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.ActivityTable,
			Columns: []string{activityparticipation.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.ActivityTable,
			Columns: []string{activityparticipation.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.UserTable,
			Columns: []string{activityparticipation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.UserTable,
			Columns: []string{activityparticipation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RewardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.RewardTable,
			Columns: []string{activityparticipation.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.RewardTable,
			Columns: []string{activityparticipation.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activityparticipation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivityParticipationUpdateOne is the builder for updating a single ActivityParticipation entity.
type ActivityParticipationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivityParticipationMutation
}

// SetActivityID sets the "activity_id" field.
func (_u *ActivityParticipationUpdateOne) SetActivityID(v int64) *ActivityParticipationUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableActivityID(v *int64) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ActivityParticipationUpdateOne) SetUserID(v int64) *ActivityParticipationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableUserID(v *int64) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParticipatedAt sets the "participated_at" field.
func (_u *ActivityParticipationUpdateOne) SetParticipatedAt(v time.Time) *ActivityParticipationUpdateOne {
	_u.mutation.SetParticipatedAt(v)
	return _u
}

// SetNillableParticipatedAt sets the "participated_at" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableParticipatedAt(v *time.Time) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetParticipatedAt(*v)
	}
	return _u
}

// SetDailyWindow sets the "daily_window" field.
func (_u *ActivityParticipationUpdateOne) SetDailyWindow(v time.Time) *ActivityParticipationUpdateOne {
	_u.mutation.SetDailyWindow(v)
	return _u
}

// SetNillableDailyWindow sets the "daily_window" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableDailyWindow(v *time.Time) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetDailyWindow(*v)
	}
	return _u
}

// SetWeeklyWindow sets the "weekly_window" field.
func (_u *ActivityParticipationUpdateOne) SetWeeklyWindow(v time.Time) *ActivityParticipationUpdateOne {
	_u.mutation.SetWeeklyWindow(v)
	return _u
}

// SetNillableWeeklyWindow sets the "weekly_window" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableWeeklyWindow(v *time.Time) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetWeeklyWindow(*v)
	}
	return _u
}

// SetMonthlyWindow sets the "monthly_window" field.
func (_u *ActivityParticipationUpdateOne) SetMonthlyWindow(v time.Time) *ActivityParticipationUpdateOne {
	_u.mutation.SetMonthlyWindow(v)
	return _u
}

// SetNillableMonthlyWindow sets the "monthly_window" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableMonthlyWindow(v *time.Time) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetMonthlyWindow(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ActivityParticipationUpdateOne) SetResult(v activityparticipation.Result) *ActivityParticipationUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableResult(v *activityparticipation.Result) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetRewardsReceived sets the "rewards_received" field.
func (_u *ActivityParticipationUpdateOne) SetRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpdateOne {
	_u.mutation.SetRewardsReceived(v)
	return _u
}

// AppendRewardsReceived appends value to the "rewards_received" field.
func (_u *ActivityParticipationUpdateOne) AppendRewardsReceived(v []map[string]interface{}) *ActivityParticipationUpdateOne {
	_u.mutation.AppendRewardsReceived(v)
	return _u
}

// ClearRewardsReceived clears the value of the "rewards_received" field.
func (_u *ActivityParticipationUpdateOne) ClearRewardsReceived() *ActivityParticipationUpdateOne {
	_u.mutation.ClearRewardsReceived()
	return _u
}

// SetRewardID sets the "reward_id" field.
func (_u *ActivityParticipationUpdateOne) SetRewardID(v int64) *ActivityParticipationUpdateOne {
	_u.mutation.SetRewardID(v)
	return _u
}

// SetNillableRewardID sets the "reward_id" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableRewardID(v *int64) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetRewardID(*v)
	}
	return _u
}

// ClearRewardID clears the value of the "reward_id" field.
func (_u *ActivityParticipationUpdateOne) ClearRewardID() *ActivityParticipationUpdateOne {
	_u.mutation.ClearRewardID()
	return _u
}

// SetCostBalance sets the "cost_balance" field.
func (_u *ActivityParticipationUpdateOne) SetCostBalance(v string) *ActivityParticipationUpdateOne {
	_u.mutation.SetCostBalance(v)
	return _u
}

// SetNillableCostBalance sets the "cost_balance" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableCostBalance(v *string) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetCostBalance(*v)
	}
	return _u
}

// SetExtraData sets the "extra_data" field.
func (_u *ActivityParticipationUpdateOne) SetExtraData(v map[string]interface{}) *ActivityParticipationUpdateOne {
	_u.mutation.SetExtraData(v)
	return _u
}

// ClearExtraData clears the value of the "extra_data" field.
func (_u *ActivityParticipationUpdateOne) ClearExtraData() *ActivityParticipationUpdateOne {
	_u.mutation.ClearExtraData()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ActivityParticipationUpdateOne) SetIPAddress(v string) *ActivityParticipationUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableIPAddress(v *string) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ActivityParticipationUpdateOne) SetUserAgent(v string) *ActivityParticipationUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ActivityParticipationUpdateOne) SetNillableUserAgent(v *string) *ActivityParticipationUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetActivity sets the "activity" edge to the Activity entity.
func (_u *ActivityParticipationUpdateOne) SetActivity(v *Activity) *ActivityParticipationUpdateOne {
	return _u.SetActivityID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ActivityParticipationUpdateOne) SetUser(v *User) *ActivityParticipationUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetReward sets the "reward" edge to the ActivityReward entity.
func (_u *ActivityParticipationUpdateOne) SetReward(v *ActivityReward) *ActivityParticipationUpdateOne {
	return _u.SetRewardID(v.ID)
}

// Mutation returns the ActivityParticipationMutation object of the builder.
func (_u *ActivityParticipationUpdateOne) Mutation() *ActivityParticipationMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the Activity entity.
func (_u *ActivityParticipationUpdateOne) ClearActivity() *ActivityParticipationUpdateOne {
	_u.mutation.ClearActivity()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ActivityParticipationUpdateOne) ClearUser() *ActivityParticipationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearReward clears the "reward" edge to the ActivityReward entity.
func (_u *ActivityParticipationUpdateOne) ClearReward() *ActivityParticipationUpdateOne {
	_u.mutation.ClearReward()
	return _u
}

// Where appends a list predicates to the ActivityParticipationUpdate builder.
func (_u *ActivityParticipationUpdateOne) Where(ps ...predicate.ActivityParticipation) *ActivityParticipationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivityParticipationUpdateOne) Select(field string, fields ...string) *ActivityParticipationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActivityParticipation entity.
func (_u *ActivityParticipationUpdateOne) Save(ctx context.Context) (*ActivityParticipation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityParticipationUpdateOne) SaveX(ctx context.Context) *ActivityParticipation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivityParticipationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityParticipationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityParticipationUpdateOne) check() error {
	if v, ok := _u.mutation.Result(); ok {
		if err := activityparticipation.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ActivityParticipation.result": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityParticipation.activity"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityParticipation.user"`)
	}
	return nil
}

func (_u *ActivityParticipationUpdateOne) sqlSave(ctx context.Context) (_node *ActivityParticipation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activityparticipation.Table, activityparticipation.Columns, sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActivityParticipation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activityparticipation.FieldID)
		for _, f := range fields {
			if !activityparticipation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activityparticipation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParticipatedAt(); ok {
		_spec.SetField(activityparticipation.FieldParticipatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyWindow(); ok {
		_spec.SetField(activityparticipation.FieldDailyWindow, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WeeklyWindow(); ok {
		_spec.SetField(activityparticipation.FieldWeeklyWindow, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MonthlyWindow(); ok {
		_spec.SetField(activityparticipation.FieldMonthlyWindow, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(activityparticipation.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RewardsReceived(); ok {
		_spec.SetField(activityparticipation.FieldRewardsReceived, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRewardsReceived(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, activityparticipation.FieldRewardsReceived, value)
		})
	}
	if _u.mutation.RewardsReceivedCleared() {
		_spec.ClearField(activityparticipation.FieldRewardsReceived, field.TypeJSON)
	}
	if value, ok := _u.mutation.CostBalance(); ok {
		_spec.SetField(activityparticipation.FieldCostBalance, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtraData(); ok {
		_spec.SetField(activityparticipation.FieldExtraData, field.TypeJSON, value)
	}
	if _u.mutation.ExtraDataCleared() {
		_spec.ClearField(activityparticipation.FieldExtraData, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(activityparticipation.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(activityparticipation.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.ActivityTable,
			Columns: []string{activityparticipation.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.ActivityTable,
			Columns: []string{activityparticipation.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.UserTable,
			Columns: []string{activityparticipation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.UserTable,
			Columns: []string{activityparticipation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RewardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.RewardTable,
			Columns: []string{activityparticipation.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityparticipation.RewardTable,
			Columns: []string{activityparticipation.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActivityParticipation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activityparticipation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
