// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
)

// ActivityCreate is the builder for creating a Activity entity.
type ActivityCreate struct {
	config
	mutation *ActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ActivityCreate) SetName(v string) *ActivityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ActivityCreate) SetDescription(v string) *ActivityCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableDescription(v *string) *ActivityCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ActivityCreate) SetIcon(v string) *ActivityCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableIcon(v *string) *ActivityCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ActivityCreate) SetType(v activity.Type) *ActivityCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ActivityCreate) SetStatus(v activity.Status) *ActivityCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableStatus(v *activity.Status) *ActivityCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ActivityCreate) SetSortOrder(v int) *ActivityCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableSortOrder(v *int) *ActivityCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *ActivityCreate) SetStartsAt(v time.Time) *ActivityCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableStartsAt(v *time.Time) *ActivityCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *ActivityCreate) SetEndsAt(v time.Time) *ActivityCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableEndsAt(v *time.Time) *ActivityCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetVisibilityRules sets the "visibility_rules" field.
func (_c *ActivityCreate) SetVisibilityRules(v map[string]interface{}) *ActivityCreate {
	_c.mutation.SetVisibilityRules(v)
	return _c
}

// SetParticipationConfig sets the "participation_config" field.
func (_c *ActivityCreate) SetParticipationConfig(v map[string]interface{}) *ActivityCreate {
	_c.mutation.SetParticipationConfig(v)
	return _c
}

// SetActivityConfig sets the "activity_config" field.
func (_c *ActivityCreate) SetActivityConfig(v map[string]interface{}) *ActivityCreate {
	_c.mutation.SetActivityConfig(v)
	return _c
}

// SetTotalParticipations sets the "total_participations" field.
func (_c *ActivityCreate) SetTotalParticipations(v int64) *ActivityCreate {
	_c.mutation.SetTotalParticipations(v)
	return _c
}

// SetNillableTotalParticipations sets the "total_participations" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableTotalParticipations(v *int64) *ActivityCreate {
	if v != nil {
		_c.SetTotalParticipations(*v)
	}
	return _c
}

// SetTotalRewardsDistributed sets the "total_rewards_distributed" field.
func (_c *ActivityCreate) SetTotalRewardsDistributed(v int64) *ActivityCreate {
	_c.mutation.SetTotalRewardsDistributed(v)
	return _c
}

// SetNillableTotalRewardsDistributed sets the "total_rewards_distributed" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableTotalRewardsDistributed(v *int64) *ActivityCreate {
	if v != nil {
		_c.SetTotalRewardsDistributed(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ActivityCreate) SetCreatedBy(v string) *ActivityCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableCreatedBy(v *string) *ActivityCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivityCreate) SetCreatedAt(v time.Time) *ActivityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableCreatedAt(v *time.Time) *ActivityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActivityCreate) SetUpdatedAt(v time.Time) *ActivityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActivityCreate) SetNillableUpdatedAt(v *time.Time) *ActivityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ActivityCreate) SetID(v int64) *ActivityCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRewardIDs adds the "rewards" edge to the ActivityReward entity by IDs.
func (_c *ActivityCreate) AddRewardIDs(ids ...int64) *ActivityCreate {
	_c.mutation.AddRewardIDs(ids...)
	return _c
}

// AddRewards adds the "rewards" edges to the ActivityReward entity.
func (_c *ActivityCreate) AddRewards(v ...*ActivityReward) *ActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRewardIDs(ids...)
}

// AddParticipationIDs adds the "participations" edge to the ActivityParticipation entity by IDs.
func (_c *ActivityCreate) AddParticipationIDs(ids ...int64) *ActivityCreate {
	_c.mutation.AddParticipationIDs(ids...)
	return _c
}

// AddParticipations adds the "participations" edges to the ActivityParticipation entity.
func (_c *ActivityCreate) AddParticipations(v ...*ActivityParticipation) *ActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipationIDs(ids...)
}

// Mutation returns the ActivityMutation object of the builder.
func (_c *ActivityCreate) Mutation() *ActivityMutation {
	return _c.mutation
}

// Save creates the Activity in the database.
func (_c *ActivityCreate) Save(ctx context.Context) (*Activity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivityCreate) SaveX(ctx context.Context) *Activity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivityCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := activity.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := activity.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := activity.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := activity.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.TotalParticipations(); !ok {
		v := activity.DefaultTotalParticipations
		_c.mutation.SetTotalParticipations(v)
	}
	if _, ok := _c.mutation.TotalRewardsDistributed(); !ok {
		v := activity.DefaultTotalRewardsDistributed
		_c.mutation.SetTotalRewardsDistributed(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := activity.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := activity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivityCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Activity.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := activity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Activity.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Activity.description"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Activity.icon"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Activity.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := activity.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Activity.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Activity.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := activity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Activity.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Activity.sort_order"`)}
	}
	if _, ok := _c.mutation.TotalParticipations(); !ok {
		return &ValidationError{Name: "total_participations", err: errors.New(`ent: missing required field "Activity.total_participations"`)}
	}
	if _, ok := _c.mutation.TotalRewardsDistributed(); !ok {
		return &ValidationError{Name: "total_rewards_distributed", err: errors.New(`ent: missing required field "Activity.total_rewards_distributed"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Activity.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Activity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Activity.updated_at"`)}
	}
	return nil
}

func (_c *ActivityCreate) sqlSave(ctx context.Context) (*Activity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivityCreate) createSpec() (*Activity, *sqlgraph.CreateSpec) {
	var (
		_node = &Activity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activity.Table, sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(activity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(activity.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(activity.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(activity.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(activity.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(activity.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(activity.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(activity.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.VisibilityRules(); ok {
		_spec.SetField(activity.FieldVisibilityRules, field.TypeJSON, value)
		_node.VisibilityRules = value
	}
	if value, ok := _c.mutation.ParticipationConfig(); ok {
		_spec.SetField(activity.FieldParticipationConfig, field.TypeJSON, value)
		_node.ParticipationConfig = value
	}
	if value, ok := _c.mutation.ActivityConfig(); ok {
		_spec.SetField(activity.FieldActivityConfig, field.TypeJSON, value)
		_node.ActivityConfig = value
	}
	if value, ok := _c.mutation.TotalParticipations(); ok {
		_spec.SetField(activity.FieldTotalParticipations, field.TypeInt64, value)
		_node.TotalParticipations = value
	}
	if value, ok := _c.mutation.TotalRewardsDistributed(); ok {
		_spec.SetField(activity.FieldTotalRewardsDistributed, field.TypeInt64, value)
		_node.TotalRewardsDistributed = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(activity.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(activity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Activity.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityCreate) OnConflict(opts ...sql.ConflictOption) *ActivityUpsertOne {
	_c.conflict = opts
	return &ActivityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Activity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityCreate) OnConflictColumns(columns ...string) *ActivityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityUpsertOne{
		create: _c,
	}
}

type (
	// ActivityUpsertOne is the builder for "upsert"-ing
	//  one Activity node.
	ActivityUpsertOne struct {
		create *ActivityCreate
	}

	// ActivityUpsert is the "OnConflict" setter.
	ActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ActivityUpsert) SetName(v string) *ActivityUpsert {
	u.Set(activity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateName() *ActivityUpsert {
	u.SetExcluded(activity.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ActivityUpsert) SetDescription(v string) *ActivityUpsert {
	u.Set(activity.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateDescription() *ActivityUpsert {
	u.SetExcluded(activity.FieldDescription)
	return u
}

// SetIcon sets the "icon" field.
func (u *ActivityUpsert) SetIcon(v string) *ActivityUpsert {
	u.Set(activity.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateIcon() *ActivityUpsert {
	u.SetExcluded(activity.FieldIcon)
	return u
}

// SetType sets the "type" field.
func (u *ActivityUpsert) SetType(v activity.Type) *ActivityUpsert {
	u.Set(activity.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateType() *ActivityUpsert {
	u.SetExcluded(activity.FieldType)
	return u
}

// SetStatus sets the "status" field.
func (u *ActivityUpsert) SetStatus(v activity.Status) *ActivityUpsert {
	u.Set(activity.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateStatus() *ActivityUpsert {
	u.SetExcluded(activity.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ActivityUpsert) SetSortOrder(v int) *ActivityUpsert {
	u.Set(activity.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateSortOrder() *ActivityUpsert {
	u.SetExcluded(activity.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ActivityUpsert) AddSortOrder(v int) *ActivityUpsert {
	u.Add(activity.FieldSortOrder, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *ActivityUpsert) SetStartsAt(v time.Time) *ActivityUpsert {
	u.Set(activity.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateStartsAt() *ActivityUpsert {
	u.SetExcluded(activity.FieldStartsAt)
	return u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *ActivityUpsert) ClearStartsAt() *ActivityUpsert {
	u.SetNull(activity.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *ActivityUpsert) SetEndsAt(v time.Time) *ActivityUpsert {
	u.Set(activity.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateEndsAt() *ActivityUpsert {
	u.SetExcluded(activity.FieldEndsAt)
	return u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *ActivityUpsert) ClearEndsAt() *ActivityUpsert {
	u.SetNull(activity.FieldEndsAt)
	return u
}

// SetVisibilityRules sets the "visibility_rules" field.
func (u *ActivityUpsert) SetVisibilityRules(v map[string]interface{}) *ActivityUpsert {
	u.Set(activity.FieldVisibilityRules, v)
	return u
}

// UpdateVisibilityRules sets the "visibility_rules" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateVisibilityRules() *ActivityUpsert {
	u.SetExcluded(activity.FieldVisibilityRules)
	return u
}

// ClearVisibilityRules clears the value of the "visibility_rules" field.
func (u *ActivityUpsert) ClearVisibilityRules() *ActivityUpsert {
	u.SetNull(activity.FieldVisibilityRules)
	return u
}

// SetParticipationConfig sets the "participation_config" field.
func (u *ActivityUpsert) SetParticipationConfig(v map[string]interface{}) *ActivityUpsert {
	u.Set(activity.FieldParticipationConfig, v)
	return u
}

// UpdateParticipationConfig sets the "participation_config" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateParticipationConfig() *ActivityUpsert {
	u.SetExcluded(activity.FieldParticipationConfig)
	return u
}

// ClearParticipationConfig clears the value of the "participation_config" field.
func (u *ActivityUpsert) ClearParticipationConfig() *ActivityUpsert {
	u.SetNull(activity.FieldParticipationConfig)
	return u
}

// SetActivityConfig sets the "activity_config" field.
func (u *ActivityUpsert) SetActivityConfig(v map[string]interface{}) *ActivityUpsert {
	u.Set(activity.FieldActivityConfig, v)
	return u
}

// UpdateActivityConfig sets the "activity_config" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateActivityConfig() *ActivityUpsert {
	u.SetExcluded(activity.FieldActivityConfig)
	return u
}

// ClearActivityConfig clears the value of the "activity_config" field.
func (u *ActivityUpsert) ClearActivityConfig() *ActivityUpsert {
	u.SetNull(activity.FieldActivityConfig)
	return u
}

// SetTotalParticipations sets the "total_participations" field.
func (u *ActivityUpsert) SetTotalParticipations(v int64) *ActivityUpsert {
	u.Set(activity.FieldTotalParticipations, v)
	return u
}

// UpdateTotalParticipations sets the "total_participations" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateTotalParticipations() *ActivityUpsert {
	u.SetExcluded(activity.FieldTotalParticipations)
	return u
}

// AddTotalParticipations adds v to the "total_participations" field.
func (u *ActivityUpsert) AddTotalParticipations(v int64) *ActivityUpsert {
	u.Add(activity.FieldTotalParticipations, v)
	return u
}

// SetTotalRewardsDistributed sets the "total_rewards_distributed" field.
func (u *ActivityUpsert) SetTotalRewardsDistributed(v int64) *ActivityUpsert {
	u.Set(activity.FieldTotalRewardsDistributed, v)
	return u
}

// UpdateTotalRewardsDistributed sets the "total_rewards_distributed" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateTotalRewardsDistributed() *ActivityUpsert {
	u.SetExcluded(activity.FieldTotalRewardsDistributed)
	return u
}

// AddTotalRewardsDistributed adds v to the "total_rewards_distributed" field.
func (u *ActivityUpsert) AddTotalRewardsDistributed(v int64) *ActivityUpsert {
	u.Add(activity.FieldTotalRewardsDistributed, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ActivityUpsert) SetCreatedBy(v string) *ActivityUpsert {
	u.Set(activity.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateCreatedBy() *ActivityUpsert {
	u.SetExcluded(activity.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityUpsert) SetUpdatedAt(v time.Time) *ActivityUpsert {
	u.Set(activity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityUpsert) UpdateUpdatedAt() *ActivityUpsert {
	u.SetExcluded(activity.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Activity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(activity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ActivityUpsertOne) UpdateNewValues() *ActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(activity.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(activity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Activity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ActivityUpsertOne) Ignore() *ActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityUpsertOne) DoNothing() *ActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityCreate.OnConflict
// documentation for more info.
func (u *ActivityUpsertOne) Update(set func(*ActivityUpsert)) *ActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ActivityUpsertOne) SetName(v string) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateName() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ActivityUpsertOne) SetDescription(v string) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateDescription() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateDescription()
	})
}

// SetIcon sets the "icon" field.
func (u *ActivityUpsertOne) SetIcon(v string) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateIcon() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateIcon()
	})
}

// SetType sets the "type" field.
func (u *ActivityUpsertOne) SetType(v activity.Type) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateType() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *ActivityUpsertOne) SetStatus(v activity.Status) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateStatus() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ActivityUpsertOne) SetSortOrder(v int) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ActivityUpsertOne) AddSortOrder(v int) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateSortOrder() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateSortOrder()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *ActivityUpsertOne) SetStartsAt(v time.Time) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateStartsAt() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *ActivityUpsertOne) ClearStartsAt() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *ActivityUpsertOne) SetEndsAt(v time.Time) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateEndsAt() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *ActivityUpsertOne) ClearEndsAt() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearEndsAt()
	})
}

// SetVisibilityRules sets the "visibility_rules" field.
func (u *ActivityUpsertOne) SetVisibilityRules(v map[string]interface{}) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetVisibilityRules(v)
	})
}

// UpdateVisibilityRules sets the "visibility_rules" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateVisibilityRules() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateVisibilityRules()
	})
}

// ClearVisibilityRules clears the value of the "visibility_rules" field.
func (u *ActivityUpsertOne) ClearVisibilityRules() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearVisibilityRules()
	})
}

// SetParticipationConfig sets the "participation_config" field.
func (u *ActivityUpsertOne) SetParticipationConfig(v map[string]interface{}) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetParticipationConfig(v)
	})
}

// UpdateParticipationConfig sets the "participation_config" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateParticipationConfig() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateParticipationConfig()
	})
}

// ClearParticipationConfig clears the value of the "participation_config" field.
func (u *ActivityUpsertOne) ClearParticipationConfig() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearParticipationConfig()
	})
}

// SetActivityConfig sets the "activity_config" field.
func (u *ActivityUpsertOne) SetActivityConfig(v map[string]interface{}) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetActivityConfig(v)
	})
}

// UpdateActivityConfig sets the "activity_config" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateActivityConfig() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateActivityConfig()
	})
}

// ClearActivityConfig clears the value of the "activity_config" field.
func (u *ActivityUpsertOne) ClearActivityConfig() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearActivityConfig()
	})
}

// SetTotalParticipations sets the "total_participations" field.
func (u *ActivityUpsertOne) SetTotalParticipations(v int64) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetTotalParticipations(v)
	})
}

// AddTotalParticipations adds v to the "total_participations" field.
func (u *ActivityUpsertOne) AddTotalParticipations(v int64) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.AddTotalParticipations(v)
	})
}

// UpdateTotalParticipations sets the "total_participations" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateTotalParticipations() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateTotalParticipations()
	})
}

// SetTotalRewardsDistributed sets the "total_rewards_distributed" field.
func (u *ActivityUpsertOne) SetTotalRewardsDistributed(v int64) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetTotalRewardsDistributed(v)
	})
}

// AddTotalRewardsDistributed adds v to the "total_rewards_distributed" field.
func (u *ActivityUpsertOne) AddTotalRewardsDistributed(v int64) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.AddTotalRewardsDistributed(v)
	})
}

// UpdateTotalRewardsDistributed sets the "total_rewards_distributed" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateTotalRewardsDistributed() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateTotalRewardsDistributed()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ActivityUpsertOne) SetCreatedBy(v string) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateCreatedBy() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityUpsertOne) SetUpdatedAt(v time.Time) *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityUpsertOne) UpdateUpdatedAt() *ActivityUpsertOne {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ActivityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ActivityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ActivityCreateBulk is the builder for creating many Activity entities in bulk.
type ActivityCreateBulk struct {
	config
	err      error
	builders []*ActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the Activity entities in the database.
func (_c *ActivityCreateBulk) Save(ctx context.Context) ([]*Activity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Activity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivityCreateBulk) SaveX(ctx context.Context) []*Activity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Activity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *ActivityUpsertBulk {
	_c.conflict = opts
	return &ActivityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Activity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityCreateBulk) OnConflictColumns(columns ...string) *ActivityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityUpsertBulk{
		create: _c,
	}
}

// ActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of Activity nodes.
type ActivityUpsertBulk struct {
	create *ActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Activity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(activity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ActivityUpsertBulk) UpdateNewValues() *ActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(activity.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(activity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Activity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ActivityUpsertBulk) Ignore() *ActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityUpsertBulk) DoNothing() *ActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityCreateBulk.OnConflict
// documentation for more info.
func (u *ActivityUpsertBulk) Update(set func(*ActivityUpsert)) *ActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ActivityUpsertBulk) SetName(v string) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateName() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ActivityUpsertBulk) SetDescription(v string) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateDescription() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateDescription()
	})
}

// SetIcon sets the "icon" field.
func (u *ActivityUpsertBulk) SetIcon(v string) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateIcon() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateIcon()
	})
}

// SetType sets the "type" field.
func (u *ActivityUpsertBulk) SetType(v activity.Type) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateType() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *ActivityUpsertBulk) SetStatus(v activity.Status) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateStatus() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ActivityUpsertBulk) SetSortOrder(v int) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ActivityUpsertBulk) AddSortOrder(v int) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateSortOrder() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateSortOrder()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *ActivityUpsertBulk) SetStartsAt(v time.Time) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateStartsAt() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *ActivityUpsertBulk) ClearStartsAt() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *ActivityUpsertBulk) SetEndsAt(v time.Time) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateEndsAt() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *ActivityUpsertBulk) ClearEndsAt() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearEndsAt()
	})
}

// SetVisibilityRules sets the "visibility_rules" field.
func (u *ActivityUpsertBulk) SetVisibilityRules(v map[string]interface{}) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetVisibilityRules(v)
	})
}

// UpdateVisibilityRules sets the "visibility_rules" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateVisibilityRules() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateVisibilityRules()
	})
}

// ClearVisibilityRules clears the value of the "visibility_rules" field.
func (u *ActivityUpsertBulk) ClearVisibilityRules() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearVisibilityRules()
	})
}

// SetParticipationConfig sets the "participation_config" field.
func (u *ActivityUpsertBulk) SetParticipationConfig(v map[string]interface{}) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetParticipationConfig(v)
	})
}

// UpdateParticipationConfig sets the "participation_config" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateParticipationConfig() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateParticipationConfig()
	})
}

// ClearParticipationConfig clears the value of the "participation_config" field.
func (u *ActivityUpsertBulk) ClearParticipationConfig() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearParticipationConfig()
	})
}

// SetActivityConfig sets the "activity_config" field.
func (u *ActivityUpsertBulk) SetActivityConfig(v map[string]interface{}) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetActivityConfig(v)
	})
}

// UpdateActivityConfig sets the "activity_config" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateActivityConfig() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateActivityConfig()
	})
}

// ClearActivityConfig clears the value of the "activity_config" field.
func (u *ActivityUpsertBulk) ClearActivityConfig() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.ClearActivityConfig()
	})
}

// SetTotalParticipations sets the "total_participations" field.
func (u *ActivityUpsertBulk) SetTotalParticipations(v int64) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetTotalParticipations(v)
	})
}

// AddTotalParticipations adds v to the "total_participations" field.
func (u *ActivityUpsertBulk) AddTotalParticipations(v int64) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.AddTotalParticipations(v)
	})
}

// UpdateTotalParticipations sets the "total_participations" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateTotalParticipations() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateTotalParticipations()
	})
}

// SetTotalRewardsDistributed sets the "total_rewards_distributed" field.
func (u *ActivityUpsertBulk) SetTotalRewardsDistributed(v int64) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetTotalRewardsDistributed(v)
	})
}

// AddTotalRewardsDistributed adds v to the "total_rewards_distributed" field.
func (u *ActivityUpsertBulk) AddTotalRewardsDistributed(v int64) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.AddTotalRewardsDistributed(v)
	})
}

// UpdateTotalRewardsDistributed sets the "total_rewards_distributed" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateTotalRewardsDistributed() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateTotalRewardsDistributed()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ActivityUpsertBulk) SetCreatedBy(v string) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateCreatedBy() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityUpsertBulk) SetUpdatedAt(v time.Time) *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityUpsertBulk) UpdateUpdatedAt() *ActivityUpsertBulk {
	return u.Update(func(s *ActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ActivityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
