// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ActivityParticipation is the model entity for the ActivityParticipation schema.
type ActivityParticipation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 关联的活动ID
	ActivityID int64 `json:"activity_id,omitempty"`
	// 参与用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 参与时间
	ParticipatedAt time.Time `json:"participated_at,omitempty"`
	// 所属日窗口（当天0点）
	DailyWindow time.Time `json:"daily_window,omitempty"`
	// 所属周窗口（当周一0点）
	WeeklyWindow time.Time `json:"weekly_window,omitempty"`
	// 所属月窗口（当月1号0点）
	MonthlyWindow time.Time `json:"monthly_window,omitempty"`
	// 参与结果
	Result activityparticipation.Result `json:"result,omitempty"`
	// 获得的奖励列表 [{reward_id:1,type:'balance',value:'10.5'}]
	RewardsReceived []map[string]interface{} `json:"rewards_received,omitempty"`
	// 主要奖励ID（抽奖活动）
	RewardID *int64 `json:"reward_id,omitempty"`
	// 消耗的余额（某些活动需要付费参与）
	CostBalance string `json:"cost_balance,omitempty"`
	// 额外数据，如签到连续天数、任务完成详情等
	ExtraData map[string]interface{} `json:"extra_data,omitempty"`
	// 参与时的IP地址
	IPAddress string `json:"ip_address,omitempty"`
	// User Agent
	UserAgent string `json:"user_agent,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityParticipationQuery when eager-loading is set.
	Edges        ActivityParticipationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActivityParticipationEdges holds the relations/edges for other nodes in the graph.
type ActivityParticipationEdges struct {
	// Activity holds the value of the activity edge.
	Activity *Activity `json:"activity,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Reward holds the value of the reward edge.
	Reward *ActivityReward `json:"reward,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ActivityOrErr returns the Activity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityParticipationEdges) ActivityOrErr() (*Activity, error) {
	if e.Activity != nil {
		return e.Activity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: activity.Label}
	}
	return nil, &NotLoadedError{edge: "activity"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityParticipationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RewardOrErr returns the Reward value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityParticipationEdges) RewardOrErr() (*ActivityReward, error) {
	if e.Reward != nil {
		return e.Reward, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: activityreward.Label}
	}
	return nil, &NotLoadedError{edge: "reward"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActivityParticipation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activityparticipation.FieldRewardsReceived, activityparticipation.FieldExtraData:
			values[i] = new([]byte)
		case activityparticipation.FieldID, activityparticipation.FieldActivityID, activityparticipation.FieldUserID, activityparticipation.FieldRewardID:
			values[i] = new(sql.NullInt64)
		case activityparticipation.FieldResult, activityparticipation.FieldCostBalance, activityparticipation.FieldIPAddress, activityparticipation.FieldUserAgent:
			values[i] = new(sql.NullString)
		case activityparticipation.FieldParticipatedAt, activityparticipation.FieldDailyWindow, activityparticipation.FieldWeeklyWindow, activityparticipation.FieldMonthlyWindow, activityparticipation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActivityParticipation fields.
func (_m *ActivityParticipation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activityparticipation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case activityparticipation.FieldActivityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = value.Int64
			}
		case activityparticipation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case activityparticipation.FieldParticipatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field participated_at", values[i])
			} else if value.Valid {
				_m.ParticipatedAt = value.Time
			}
		case activityparticipation.FieldDailyWindow:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field daily_window", values[i])
			} else if value.Valid {
				_m.DailyWindow = value.Time
			}
		case activityparticipation.FieldWeeklyWindow:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_window", values[i])
			} else if value.Valid {
				_m.WeeklyWindow = value.Time
			}
		case activityparticipation.FieldMonthlyWindow:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_window", values[i])
			} else if value.Valid {
				_m.MonthlyWindow = value.Time
			}
		case activityparticipation.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = activityparticipation.Result(value.String)
			}
		case activityparticipation.FieldRewardsReceived:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rewards_received", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RewardsReceived); err != nil {
					return fmt.Errorf("unmarshal field rewards_received: %w", err)
				}
			}
		case activityparticipation.FieldRewardID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_id", values[i])
			} else if value.Valid {
				_m.RewardID = new(int64)
				*_m.RewardID = value.Int64
			}
		case activityparticipation.FieldCostBalance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cost_balance", values[i])
			} else if value.Valid {
				_m.CostBalance = value.String
			}
		case activityparticipation.FieldExtraData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraData); err != nil {
					return fmt.Errorf("unmarshal field extra_data: %w", err)
				}
			}
		case activityparticipation.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case activityparticipation.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case activityparticipation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActivityParticipation.
// This includes values selected through modifiers, order, etc.
func (_m *ActivityParticipation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActivity queries the "activity" edge of the ActivityParticipation entity.
func (_m *ActivityParticipation) QueryActivity() *ActivityQuery {
	return NewActivityParticipationClient(_m.config).QueryActivity(_m)
}

// QueryUser queries the "user" edge of the ActivityParticipation entity.
func (_m *ActivityParticipation) QueryUser() *UserQuery {
	return NewActivityParticipationClient(_m.config).QueryUser(_m)
}

// QueryReward queries the "reward" edge of the ActivityParticipation entity.
func (_m *ActivityParticipation) QueryReward() *ActivityRewardQuery {
	return NewActivityParticipationClient(_m.config).QueryReward(_m)
}

// Update returns a builder for updating this ActivityParticipation.
// Note that you need to call ActivityParticipation.Unwrap() before calling this method if this ActivityParticipation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActivityParticipation) Update() *ActivityParticipationUpdateOne {
	return NewActivityParticipationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActivityParticipation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActivityParticipation) Unwrap() *ActivityParticipation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActivityParticipation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActivityParticipation) String() string {
	var builder strings.Builder
	builder.WriteString("ActivityParticipation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("activity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("participated_at=")
	builder.WriteString(_m.ParticipatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("daily_window=")
	builder.WriteString(_m.DailyWindow.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("weekly_window=")
	builder.WriteString(_m.WeeklyWindow.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("monthly_window=")
	builder.WriteString(_m.MonthlyWindow.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", _m.Result))
	builder.WriteString(", ")
	builder.WriteString("rewards_received=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardsReceived))
	builder.WriteString(", ")
	if v := _m.RewardID; v != nil {
		builder.WriteString("reward_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("cost_balance=")
	builder.WriteString(_m.CostBalance)
	builder.WriteString(", ")
	builder.WriteString("extra_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraData))
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ActivityParticipations is a parsable slice of ActivityParticipation.
type ActivityParticipations []*ActivityParticipation
