// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
)

// ActivityRewardCreate is the builder for creating a ActivityReward entity.
type ActivityRewardCreate struct {
	config
	mutation *ActivityRewardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityID sets the "activity_id" field.
func (_c *ActivityRewardCreate) SetActivityID(v int64) *ActivityRewardCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ActivityRewardCreate) SetName(v string) *ActivityRewardCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ActivityRewardCreate) SetDescription(v string) *ActivityRewardCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableDescription(v *string) *ActivityRewardCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ActivityRewardCreate) SetIcon(v string) *ActivityRewardCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableIcon(v *string) *ActivityRewardCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetRewardType sets the "reward_type" field.
func (_c *ActivityRewardCreate) SetRewardType(v activityreward.RewardType) *ActivityRewardCreate {
	_c.mutation.SetRewardType(v)
	return _c
}

// SetRewardValue sets the "reward_value" field.
func (_c *ActivityRewardCreate) SetRewardValue(v string) *ActivityRewardCreate {
	_c.mutation.SetRewardValue(v)
	return _c
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableRewardValue(v *string) *ActivityRewardCreate {
	if v != nil {
		_c.SetRewardValue(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *ActivityRewardCreate) SetWeight(v int) *ActivityRewardCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableWeight(v *int) *ActivityRewardCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetProbability sets the "probability" field.
func (_c *ActivityRewardCreate) SetProbability(v float64) *ActivityRewardCreate {
	_c.mutation.SetProbability(v)
	return _c
}

// SetNillableProbability sets the "probability" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableProbability(v *float64) *ActivityRewardCreate {
	if v != nil {
		_c.SetProbability(*v)
	}
	return _c
}

// SetTotalStock sets the "total_stock" field.
func (_c *ActivityRewardCreate) SetTotalStock(v int64) *ActivityRewardCreate {
	_c.mutation.SetTotalStock(v)
	return _c
}

// SetNillableTotalStock sets the "total_stock" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableTotalStock(v *int64) *ActivityRewardCreate {
	if v != nil {
		_c.SetTotalStock(*v)
	}
	return _c
}

// SetRemainingStock sets the "remaining_stock" field.
func (_c *ActivityRewardCreate) SetRemainingStock(v int64) *ActivityRewardCreate {
	_c.mutation.SetRemainingStock(v)
	return _c
}

// SetNillableRemainingStock sets the "remaining_stock" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableRemainingStock(v *int64) *ActivityRewardCreate {
	if v != nil {
		_c.SetRemainingStock(*v)
	}
	return _c
}

// SetTier sets the "tier" field.
func (_c *ActivityRewardCreate) SetTier(v activityreward.Tier) *ActivityRewardCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableTier(v *activityreward.Tier) *ActivityRewardCreate {
	if v != nil {
		_c.SetTier(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ActivityRewardCreate) SetStatus(v activityreward.Status) *ActivityRewardCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableStatus(v *activityreward.Status) *ActivityRewardCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ActivityRewardCreate) SetSortOrder(v int) *ActivityRewardCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableSortOrder(v *int) *ActivityRewardCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetDistributedCount sets the "distributed_count" field.
func (_c *ActivityRewardCreate) SetDistributedCount(v int64) *ActivityRewardCreate {
	_c.mutation.SetDistributedCount(v)
	return _c
}

// SetNillableDistributedCount sets the "distributed_count" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableDistributedCount(v *int64) *ActivityRewardCreate {
	if v != nil {
		_c.SetDistributedCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivityRewardCreate) SetCreatedAt(v time.Time) *ActivityRewardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableCreatedAt(v *time.Time) *ActivityRewardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActivityRewardCreate) SetUpdatedAt(v time.Time) *ActivityRewardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActivityRewardCreate) SetNillableUpdatedAt(v *time.Time) *ActivityRewardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ActivityRewardCreate) SetID(v int64) *ActivityRewardCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetActivity sets the "activity" edge to the Activity entity.
func (_c *ActivityRewardCreate) SetActivity(v *Activity) *ActivityRewardCreate {
	return _c.SetActivityID(v.ID)
}

// AddParticipationIDs adds the "participations" edge to the ActivityParticipation entity by IDs.
func (_c *ActivityRewardCreate) AddParticipationIDs(ids ...int64) *ActivityRewardCreate {
	_c.mutation.AddParticipationIDs(ids...)
	return _c
}

// AddParticipations adds the "participations" edges to the ActivityParticipation entity.
func (_c *ActivityRewardCreate) AddParticipations(v ...*ActivityParticipation) *ActivityRewardCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipationIDs(ids...)
}

// Mutation returns the ActivityRewardMutation object of the builder.
func (_c *ActivityRewardCreate) Mutation() *ActivityRewardMutation {
	return _c.mutation
}

// Save creates the ActivityReward in the database.
func (_c *ActivityRewardCreate) Save(ctx context.Context) (*ActivityReward, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivityRewardCreate) SaveX(ctx context.Context) *ActivityReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityRewardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityRewardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivityRewardCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := activityreward.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := activityreward.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.RewardValue(); !ok {
		v := activityreward.DefaultRewardValue
		_c.mutation.SetRewardValue(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := activityreward.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.TotalStock(); !ok {
		v := activityreward.DefaultTotalStock
		_c.mutation.SetTotalStock(v)
	}
	if _, ok := _c.mutation.RemainingStock(); !ok {
		v := activityreward.DefaultRemainingStock
		_c.mutation.SetRemainingStock(v)
	}
	if _, ok := _c.mutation.Tier(); !ok {
		v := activityreward.DefaultTier
		_c.mutation.SetTier(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := activityreward.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := activityreward.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.DistributedCount(); !ok {
		v := activityreward.DefaultDistributedCount
		_c.mutation.SetDistributedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activityreward.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := activityreward.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivityRewardCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "ActivityReward.activity_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ActivityReward.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := activityreward.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ActivityReward.description"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "ActivityReward.icon"`)}
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		return &ValidationError{Name: "reward_type", err: errors.New(`ent: missing required field "ActivityReward.reward_type"`)}
	}
	if v, ok := _c.mutation.RewardType(); ok {
		if err := activityreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.reward_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RewardValue(); !ok {
		return &ValidationError{Name: "reward_value", err: errors.New(`ent: missing required field "ActivityReward.reward_value"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "ActivityReward.weight"`)}
	}
	if _, ok := _c.mutation.TotalStock(); !ok {
		return &ValidationError{Name: "total_stock", err: errors.New(`ent: missing required field "ActivityReward.total_stock"`)}
	}
	if _, ok := _c.mutation.RemainingStock(); !ok {
		return &ValidationError{Name: "remaining_stock", err: errors.New(`ent: missing required field "ActivityReward.remaining_stock"`)}
	}
	if _, ok := _c.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "ActivityReward.tier"`)}
	}
	if v, ok := _c.mutation.Tier(); ok {
		if err := activityreward.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ActivityReward.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := activityreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivityReward.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ActivityReward.sort_order"`)}
	}
	if _, ok := _c.mutation.DistributedCount(); !ok {
		return &ValidationError{Name: "distributed_count", err: errors.New(`ent: missing required field "ActivityReward.distributed_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivityReward.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActivityReward.updated_at"`)}
	}
	if len(_c.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "ActivityReward.activity"`)}
	}
	return nil
}

func (_c *ActivityRewardCreate) sqlSave(ctx context.Context) (*ActivityReward, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivityRewardCreate) createSpec() (*ActivityReward, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityReward{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activityreward.Table, sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(activityreward.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(activityreward.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(activityreward.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.RewardType(); ok {
		_spec.SetField(activityreward.FieldRewardType, field.TypeEnum, value)
		_node.RewardType = value
	}
	if value, ok := _c.mutation.RewardValue(); ok {
		_spec.SetField(activityreward.FieldRewardValue, field.TypeString, value)
		_node.RewardValue = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(activityreward.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Probability(); ok {
		_spec.SetField(activityreward.FieldProbability, field.TypeFloat64, value)
		_node.Probability = value
	}
	if value, ok := _c.mutation.TotalStock(); ok {
		_spec.SetField(activityreward.FieldTotalStock, field.TypeInt64, value)
		_node.TotalStock = value
	}
	if value, ok := _c.mutation.RemainingStock(); ok {
		_spec.SetField(activityreward.FieldRemainingStock, field.TypeInt64, value)
		_node.RemainingStock = value
	}
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(activityreward.FieldTier, field.TypeEnum, value)
		_node.Tier = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(activityreward.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(activityreward.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.DistributedCount(); ok {
		_spec.SetField(activityreward.FieldDistributedCount, field.TypeInt64, value)
		_node.DistributedCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activityreward.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(activityreward.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityreward.ActivityTable,
			Columns: []string{activityreward.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activityreward.ParticipationsTable,
			Columns: []string{activityreward.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityReward.Create().
//		SetActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityRewardUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityRewardCreate) OnConflict(opts ...sql.ConflictOption) *ActivityRewardUpsertOne {
	_c.conflict = opts
	return &ActivityRewardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityRewardCreate) OnConflictColumns(columns ...string) *ActivityRewardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityRewardUpsertOne{
		create: _c,
	}
}

type (
	// ActivityRewardUpsertOne is the builder for "upsert"-ing
	//  one ActivityReward node.
	ActivityRewardUpsertOne struct {
		create *ActivityRewardCreate
	}

	// ActivityRewardUpsert is the "OnConflict" setter.
	ActivityRewardUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityID sets the "activity_id" field.
func (u *ActivityRewardUpsert) SetActivityID(v int64) *ActivityRewardUpsert {
	u.Set(activityreward.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateActivityID() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldActivityID)
	return u
}

// SetName sets the "name" field.
func (u *ActivityRewardUpsert) SetName(v string) *ActivityRewardUpsert {
	u.Set(activityreward.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateName() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ActivityRewardUpsert) SetDescription(v string) *ActivityRewardUpsert {
	u.Set(activityreward.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateDescription() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldDescription)
	return u
}

// SetIcon sets the "icon" field.
func (u *ActivityRewardUpsert) SetIcon(v string) *ActivityRewardUpsert {
	u.Set(activityreward.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateIcon() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldIcon)
	return u
}

// SetRewardType sets the "reward_type" field.
func (u *ActivityRewardUpsert) SetRewardType(v activityreward.RewardType) *ActivityRewardUpsert {
	u.Set(activityreward.FieldRewardType, v)
	return u
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateRewardType() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldRewardType)
	return u
}

// SetRewardValue sets the "reward_value" field.
func (u *ActivityRewardUpsert) SetRewardValue(v string) *ActivityRewardUpsert {
	u.Set(activityreward.FieldRewardValue, v)
	return u
}

// UpdateRewardValue sets the "reward_value" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateRewardValue() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldRewardValue)
	return u
}

// SetWeight sets the "weight" field.
func (u *ActivityRewardUpsert) SetWeight(v int) *ActivityRewardUpsert {
	u.Set(activityreward.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateWeight() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *ActivityRewardUpsert) AddWeight(v int) *ActivityRewardUpsert {
	u.Add(activityreward.FieldWeight, v)
	return u
}

// SetProbability sets the "probability" field.
func (u *ActivityRewardUpsert) SetProbability(v float64) *ActivityRewardUpsert {
	u.Set(activityreward.FieldProbability, v)
	return u
}

// UpdateProbability sets the "probability" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateProbability() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldProbability)
	return u
}

// AddProbability adds v to the "probability" field.
func (u *ActivityRewardUpsert) AddProbability(v float64) *ActivityRewardUpsert {
	u.Add(activityreward.FieldProbability, v)
	return u
}

// ClearProbability clears the value of the "probability" field.
func (u *ActivityRewardUpsert) ClearProbability() *ActivityRewardUpsert {
	u.SetNull(activityreward.FieldProbability)
	return u
}

// SetTotalStock sets the "total_stock" field.
func (u *ActivityRewardUpsert) SetTotalStock(v int64) *ActivityRewardUpsert {
	u.Set(activityreward.FieldTotalStock, v)
	return u
}

// UpdateTotalStock sets the "total_stock" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateTotalStock() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldTotalStock)
	return u
}

// AddTotalStock adds v to the "total_stock" field.
func (u *ActivityRewardUpsert) AddTotalStock(v int64) *ActivityRewardUpsert {
	u.Add(activityreward.FieldTotalStock, v)
	return u
}

// SetRemainingStock sets the "remaining_stock" field.
func (u *ActivityRewardUpsert) SetRemainingStock(v int64) *ActivityRewardUpsert {
	u.Set(activityreward.FieldRemainingStock, v)
	return u
}

// UpdateRemainingStock sets the "remaining_stock" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateRemainingStock() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldRemainingStock)
	return u
}

// AddRemainingStock adds v to the "remaining_stock" field.
func (u *ActivityRewardUpsert) AddRemainingStock(v int64) *ActivityRewardUpsert {
	u.Add(activityreward.FieldRemainingStock, v)
	return u
}

// SetTier sets the "tier" field.
func (u *ActivityRewardUpsert) SetTier(v activityreward.Tier) *ActivityRewardUpsert {
	u.Set(activityreward.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateTier() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldTier)
	return u
}

// SetStatus sets the "status" field.
func (u *ActivityRewardUpsert) SetStatus(v activityreward.Status) *ActivityRewardUpsert {
	u.Set(activityreward.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateStatus() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ActivityRewardUpsert) SetSortOrder(v int) *ActivityRewardUpsert {
	u.Set(activityreward.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateSortOrder() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ActivityRewardUpsert) AddSortOrder(v int) *ActivityRewardUpsert {
	u.Add(activityreward.FieldSortOrder, v)
	return u
}

// SetDistributedCount sets the "distributed_count" field.
func (u *ActivityRewardUpsert) SetDistributedCount(v int64) *ActivityRewardUpsert {
	u.Set(activityreward.FieldDistributedCount, v)
	return u
}

// UpdateDistributedCount sets the "distributed_count" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateDistributedCount() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldDistributedCount)
	return u
}

// AddDistributedCount adds v to the "distributed_count" field.
func (u *ActivityRewardUpsert) AddDistributedCount(v int64) *ActivityRewardUpsert {
	u.Add(activityreward.FieldDistributedCount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityRewardUpsert) SetUpdatedAt(v time.Time) *ActivityRewardUpsert {
	u.Set(activityreward.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityRewardUpsert) UpdateUpdatedAt() *ActivityRewardUpsert {
	u.SetExcluded(activityreward.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ActivityReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(activityreward.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ActivityRewardUpsertOne) UpdateNewValues() *ActivityRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(activityreward.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(activityreward.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityReward.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ActivityRewardUpsertOne) Ignore() *ActivityRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityRewardUpsertOne) DoNothing() *ActivityRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityRewardCreate.OnConflict
// documentation for more info.
func (u *ActivityRewardUpsertOne) Update(set func(*ActivityRewardUpsert)) *ActivityRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *ActivityRewardUpsertOne) SetActivityID(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateActivityID() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateActivityID()
	})
}

// SetName sets the "name" field.
func (u *ActivityRewardUpsertOne) SetName(v string) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateName() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ActivityRewardUpsertOne) SetDescription(v string) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateDescription() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateDescription()
	})
}

// SetIcon sets the "icon" field.
func (u *ActivityRewardUpsertOne) SetIcon(v string) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateIcon() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateIcon()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *ActivityRewardUpsertOne) SetRewardType(v activityreward.RewardType) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateRewardType() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardValue sets the "reward_value" field.
func (u *ActivityRewardUpsertOne) SetRewardValue(v string) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetRewardValue(v)
	})
}

// UpdateRewardValue sets the "reward_value" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateRewardValue() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateRewardValue()
	})
}

// SetWeight sets the "weight" field.
func (u *ActivityRewardUpsertOne) SetWeight(v int) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ActivityRewardUpsertOne) AddWeight(v int) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateWeight() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateWeight()
	})
}

// SetProbability sets the "probability" field.
func (u *ActivityRewardUpsertOne) SetProbability(v float64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetProbability(v)
	})
}

// AddProbability adds v to the "probability" field.
func (u *ActivityRewardUpsertOne) AddProbability(v float64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddProbability(v)
	})
}

// UpdateProbability sets the "probability" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateProbability() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateProbability()
	})
}

// ClearProbability clears the value of the "probability" field.
func (u *ActivityRewardUpsertOne) ClearProbability() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.ClearProbability()
	})
}

// SetTotalStock sets the "total_stock" field.
func (u *ActivityRewardUpsertOne) SetTotalStock(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetTotalStock(v)
	})
}

// AddTotalStock adds v to the "total_stock" field.
func (u *ActivityRewardUpsertOne) AddTotalStock(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddTotalStock(v)
	})
}

// UpdateTotalStock sets the "total_stock" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateTotalStock() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateTotalStock()
	})
}

// SetRemainingStock sets the "remaining_stock" field.
func (u *ActivityRewardUpsertOne) SetRemainingStock(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetRemainingStock(v)
	})
}

// AddRemainingStock adds v to the "remaining_stock" field.
func (u *ActivityRewardUpsertOne) AddRemainingStock(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddRemainingStock(v)
	})
}

// UpdateRemainingStock sets the "remaining_stock" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateRemainingStock() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateRemainingStock()
	})
}

// SetTier sets the "tier" field.
func (u *ActivityRewardUpsertOne) SetTier(v activityreward.Tier) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateTier() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateTier()
	})
}

// SetStatus sets the "status" field.
func (u *ActivityRewardUpsertOne) SetStatus(v activityreward.Status) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateStatus() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ActivityRewardUpsertOne) SetSortOrder(v int) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ActivityRewardUpsertOne) AddSortOrder(v int) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateSortOrder() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateSortOrder()
	})
}

// SetDistributedCount sets the "distributed_count" field.
func (u *ActivityRewardUpsertOne) SetDistributedCount(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetDistributedCount(v)
	})
}

// AddDistributedCount adds v to the "distributed_count" field.
func (u *ActivityRewardUpsertOne) AddDistributedCount(v int64) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddDistributedCount(v)
	})
}

// UpdateDistributedCount sets the "distributed_count" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateDistributedCount() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateDistributedCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityRewardUpsertOne) SetUpdatedAt(v time.Time) *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityRewardUpsertOne) UpdateUpdatedAt() *ActivityRewardUpsertOne {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ActivityRewardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityRewardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityRewardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ActivityRewardUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ActivityRewardUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ActivityRewardCreateBulk is the builder for creating many ActivityReward entities in bulk.
type ActivityRewardCreateBulk struct {
	config
	err      error
	builders []*ActivityRewardCreate
	conflict []sql.ConflictOption
}

// Save creates the ActivityReward entities in the database.
func (_c *ActivityRewardCreateBulk) Save(ctx context.Context) ([]*ActivityReward, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActivityReward, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityRewardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivityRewardCreateBulk) SaveX(ctx context.Context) []*ActivityReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityRewardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityRewardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityReward.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityRewardUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityRewardCreateBulk) OnConflict(opts ...sql.ConflictOption) *ActivityRewardUpsertBulk {
	_c.conflict = opts
	return &ActivityRewardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityRewardCreateBulk) OnConflictColumns(columns ...string) *ActivityRewardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityRewardUpsertBulk{
		create: _c,
	}
}

// ActivityRewardUpsertBulk is the builder for "upsert"-ing
// a bulk of ActivityReward nodes.
type ActivityRewardUpsertBulk struct {
	create *ActivityRewardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ActivityReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(activityreward.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ActivityRewardUpsertBulk) UpdateNewValues() *ActivityRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(activityreward.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(activityreward.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityReward.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ActivityRewardUpsertBulk) Ignore() *ActivityRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityRewardUpsertBulk) DoNothing() *ActivityRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityRewardCreateBulk.OnConflict
// documentation for more info.
func (u *ActivityRewardUpsertBulk) Update(set func(*ActivityRewardUpsert)) *ActivityRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *ActivityRewardUpsertBulk) SetActivityID(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateActivityID() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateActivityID()
	})
}

// SetName sets the "name" field.
func (u *ActivityRewardUpsertBulk) SetName(v string) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateName() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ActivityRewardUpsertBulk) SetDescription(v string) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateDescription() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateDescription()
	})
}

// SetIcon sets the "icon" field.
func (u *ActivityRewardUpsertBulk) SetIcon(v string) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateIcon() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateIcon()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *ActivityRewardUpsertBulk) SetRewardType(v activityreward.RewardType) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateRewardType() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardValue sets the "reward_value" field.
func (u *ActivityRewardUpsertBulk) SetRewardValue(v string) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetRewardValue(v)
	})
}

// UpdateRewardValue sets the "reward_value" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateRewardValue() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateRewardValue()
	})
}

// SetWeight sets the "weight" field.
func (u *ActivityRewardUpsertBulk) SetWeight(v int) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ActivityRewardUpsertBulk) AddWeight(v int) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateWeight() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateWeight()
	})
}

// SetProbability sets the "probability" field.
func (u *ActivityRewardUpsertBulk) SetProbability(v float64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetProbability(v)
	})
}

// AddProbability adds v to the "probability" field.
func (u *ActivityRewardUpsertBulk) AddProbability(v float64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddProbability(v)
	})
}

// UpdateProbability sets the "probability" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateProbability() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateProbability()
	})
}

// ClearProbability clears the value of the "probability" field.
func (u *ActivityRewardUpsertBulk) ClearProbability() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.ClearProbability()
	})
}

// SetTotalStock sets the "total_stock" field.
func (u *ActivityRewardUpsertBulk) SetTotalStock(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetTotalStock(v)
	})
}

// AddTotalStock adds v to the "total_stock" field.
func (u *ActivityRewardUpsertBulk) AddTotalStock(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddTotalStock(v)
	})
}

// UpdateTotalStock sets the "total_stock" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateTotalStock() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateTotalStock()
	})
}

// SetRemainingStock sets the "remaining_stock" field.
func (u *ActivityRewardUpsertBulk) SetRemainingStock(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetRemainingStock(v)
	})
}

// AddRemainingStock adds v to the "remaining_stock" field.
func (u *ActivityRewardUpsertBulk) AddRemainingStock(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddRemainingStock(v)
	})
}

// UpdateRemainingStock sets the "remaining_stock" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateRemainingStock() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateRemainingStock()
	})
}

// SetTier sets the "tier" field.
func (u *ActivityRewardUpsertBulk) SetTier(v activityreward.Tier) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateTier() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateTier()
	})
}

// SetStatus sets the "status" field.
func (u *ActivityRewardUpsertBulk) SetStatus(v activityreward.Status) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateStatus() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ActivityRewardUpsertBulk) SetSortOrder(v int) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ActivityRewardUpsertBulk) AddSortOrder(v int) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateSortOrder() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateSortOrder()
	})
}

// SetDistributedCount sets the "distributed_count" field.
func (u *ActivityRewardUpsertBulk) SetDistributedCount(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetDistributedCount(v)
	})
}

// AddDistributedCount adds v to the "distributed_count" field.
func (u *ActivityRewardUpsertBulk) AddDistributedCount(v int64) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.AddDistributedCount(v)
	})
}

// UpdateDistributedCount sets the "distributed_count" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateDistributedCount() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateDistributedCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityRewardUpsertBulk) SetUpdatedAt(v time.Time) *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityRewardUpsertBulk) UpdateUpdatedAt() *ActivityRewardUpsertBulk {
	return u.Update(func(s *ActivityRewardUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ActivityRewardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ActivityRewardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityRewardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityRewardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
