// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activity"
	"github.com/Wei-Shaw/sub2api/ent/activityparticipation"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ActivityUpdate is the builder for updating Activity entities.
type ActivityUpdate struct {
	config
	hooks    []Hook
	mutation *ActivityMutation
}

// Where appends a list predicates to the ActivityUpdate builder.
func (_u *ActivityUpdate) Where(ps ...predicate.Activity) *ActivityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ActivityUpdate) SetName(v string) *ActivityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableName(v *string) *ActivityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActivityUpdate) SetDescription(v string) *ActivityUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableDescription(v *string) *ActivityUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ActivityUpdate) SetIcon(v string) *ActivityUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableIcon(v *string) *ActivityUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ActivityUpdate) SetType(v activity.Type) *ActivityUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableType(v *activity.Type) *ActivityUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ActivityUpdate) SetStatus(v activity.Status) *ActivityUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableStatus(v *activity.Status) *ActivityUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ActivityUpdate) SetSortOrder(v int) *ActivityUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableSortOrder(v *int) *ActivityUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ActivityUpdate) AddSortOrder(v int) *ActivityUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *ActivityUpdate) SetStartsAt(v time.Time) *ActivityUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableStartsAt(v *time.Time) *ActivityUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *ActivityUpdate) ClearStartsAt() *ActivityUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *ActivityUpdate) SetEndsAt(v time.Time) *ActivityUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableEndsAt(v *time.Time) *ActivityUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *ActivityUpdate) ClearEndsAt() *ActivityUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetVisibilityRules sets the "visibility_rules" field.
func (_u *ActivityUpdate) SetVisibilityRules(v map[string]interface{}) *ActivityUpdate {
	_u.mutation.SetVisibilityRules(v)
	return _u
}

// ClearVisibilityRules clears the value of the "visibility_rules" field.
func (_u *ActivityUpdate) ClearVisibilityRules() *ActivityUpdate {
	_u.mutation.ClearVisibilityRules()
	return _u
}

// SetParticipationConfig sets the "participation_config" field.
func (_u *ActivityUpdate) SetParticipationConfig(v map[string]interface{}) *ActivityUpdate {
	_u.mutation.SetParticipationConfig(v)
	return _u
}

// ClearParticipationConfig clears the value of the "participation_config" field.
func (_u *ActivityUpdate) ClearParticipationConfig() *ActivityUpdate {
	_u.mutation.ClearParticipationConfig()
	return _u
}

// SetActivityConfig sets the "activity_config" field.
func (_u *ActivityUpdate) SetActivityConfig(v map[string]interface{}) *ActivityUpdate {
	_u.mutation.SetActivityConfig(v)
	return _u
}

// ClearActivityConfig clears the value of the "activity_config" field.
func (_u *ActivityUpdate) ClearActivityConfig() *ActivityUpdate {
	_u.mutation.ClearActivityConfig()
	return _u
}

// SetTotalParticipations sets the "total_participations" field.
func (_u *ActivityUpdate) SetTotalParticipations(v int64) *ActivityUpdate {
	_u.mutation.ResetTotalParticipations()
	_u.mutation.SetTotalParticipations(v)
	return _u
}

// SetNillableTotalParticipations sets the "total_participations" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableTotalParticipations(v *int64) *ActivityUpdate {
	if v != nil {
		_u.SetTotalParticipations(*v)
	}
	return _u
}

// AddTotalParticipations adds value to the "total_participations" field.
func (_u *ActivityUpdate) AddTotalParticipations(v int64) *ActivityUpdate {
	_u.mutation.AddTotalParticipations(v)
	return _u
}

// SetTotalRewardsDistributed sets the "total_rewards_distributed" field.
func (_u *ActivityUpdate) SetTotalRewardsDistributed(v int64) *ActivityUpdate {
	_u.mutation.ResetTotalRewardsDistributed()
	_u.mutation.SetTotalRewardsDistributed(v)
	return _u
}

// SetNillableTotalRewardsDistributed sets the "total_rewards_distributed" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableTotalRewardsDistributed(v *int64) *ActivityUpdate {
	if v != nil {
		_u.SetTotalRewardsDistributed(*v)
	}
	return _u
}

// AddTotalRewardsDistributed adds value to the "total_rewards_distributed" field.
func (_u *ActivityUpdate) AddTotalRewardsDistributed(v int64) *ActivityUpdate {
	_u.mutation.AddTotalRewardsDistributed(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ActivityUpdate) SetCreatedBy(v string) *ActivityUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ActivityUpdate) SetNillableCreatedBy(v *string) *ActivityUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivityUpdate) SetUpdatedAt(v time.Time) *ActivityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRewardIDs adds the "rewards" edge to the ActivityReward entity by IDs.
func (_u *ActivityUpdate) AddRewardIDs(ids ...int64) *ActivityUpdate {
	_u.mutation.AddRewardIDs(ids...)
	return _u
}

// AddRewards adds the "rewards" edges to the ActivityReward entity.
func (_u *ActivityUpdate) AddRewards(v ...*ActivityReward) *ActivityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRewardIDs(ids...)
}

// AddParticipationIDs adds the "participations" edge to the ActivityParticipation entity by IDs.
func (_u *ActivityUpdate) AddParticipationIDs(ids ...int64) *ActivityUpdate {
	_u.mutation.AddParticipationIDs(ids...)
	return _u
}

// AddParticipations adds the "participations" edges to the ActivityParticipation entity.
func (_u *ActivityUpdate) AddParticipations(v ...*ActivityParticipation) *ActivityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipationIDs(ids...)
}

// Mutation returns the ActivityMutation object of the builder.
func (_u *ActivityUpdate) Mutation() *ActivityMutation {
	return _u.mutation
}

// ClearRewards clears all "rewards" edges to the ActivityReward entity.
func (_u *ActivityUpdate) ClearRewards() *ActivityUpdate {
	_u.mutation.ClearRewards()
	return _u
}

// RemoveRewardIDs removes the "rewards" edge to ActivityReward entities by IDs.
func (_u *ActivityUpdate) RemoveRewardIDs(ids ...int64) *ActivityUpdate {
	_u.mutation.RemoveRewardIDs(ids...)
	return _u
}

// RemoveRewards removes "rewards" edges to ActivityReward entities.
func (_u *ActivityUpdate) RemoveRewards(v ...*ActivityReward) *ActivityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRewardIDs(ids...)
}

// ClearParticipations clears all "participations" edges to the ActivityParticipation entity.
func (_u *ActivityUpdate) ClearParticipations() *ActivityUpdate {
	_u.mutation.ClearParticipations()
	return _u
}

// RemoveParticipationIDs removes the "participations" edge to ActivityParticipation entities by IDs.
func (_u *ActivityUpdate) RemoveParticipationIDs(ids ...int64) *ActivityUpdate {
	_u.mutation.RemoveParticipationIDs(ids...)
	return _u
}

// RemoveParticipations removes "participations" edges to ActivityParticipation entities.
func (_u *ActivityUpdate) RemoveParticipations(v ...*ActivityParticipation) *ActivityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := activity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := activity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Activity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := activity.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Activity.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := activity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Activity.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activity.Table, activity.Columns, sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(activity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(activity.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(activity.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(activity.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(activity.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(activity.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(activity.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(activity.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(activity.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(activity.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(activity.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VisibilityRules(); ok {
		_spec.SetField(activity.FieldVisibilityRules, field.TypeJSON, value)
	}
	if _u.mutation.VisibilityRulesCleared() {
		_spec.ClearField(activity.FieldVisibilityRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParticipationConfig(); ok {
		_spec.SetField(activity.FieldParticipationConfig, field.TypeJSON, value)
	}
	if _u.mutation.ParticipationConfigCleared() {
		_spec.ClearField(activity.FieldParticipationConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActivityConfig(); ok {
		_spec.SetField(activity.FieldActivityConfig, field.TypeJSON, value)
	}
	if _u.mutation.ActivityConfigCleared() {
		_spec.ClearField(activity.FieldActivityConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.TotalParticipations(); ok {
		_spec.SetField(activity.FieldTotalParticipations, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalParticipations(); ok {
		_spec.AddField(activity.FieldTotalParticipations, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalRewardsDistributed(); ok {
		_spec.SetField(activity.FieldTotalRewardsDistributed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRewardsDistributed(); ok {
		_spec.AddField(activity.FieldTotalRewardsDistributed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(activity.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRewardsIDs(); len(nodes) > 0 && !_u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivityUpdateOne is the builder for updating a single Activity entity.
type ActivityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivityMutation
}

// SetName sets the "name" field.
func (_u *ActivityUpdateOne) SetName(v string) *ActivityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableName(v *string) *ActivityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActivityUpdateOne) SetDescription(v string) *ActivityUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableDescription(v *string) *ActivityUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ActivityUpdateOne) SetIcon(v string) *ActivityUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableIcon(v *string) *ActivityUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ActivityUpdateOne) SetType(v activity.Type) *ActivityUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableType(v *activity.Type) *ActivityUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ActivityUpdateOne) SetStatus(v activity.Status) *ActivityUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableStatus(v *activity.Status) *ActivityUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ActivityUpdateOne) SetSortOrder(v int) *ActivityUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableSortOrder(v *int) *ActivityUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ActivityUpdateOne) AddSortOrder(v int) *ActivityUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *ActivityUpdateOne) SetStartsAt(v time.Time) *ActivityUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableStartsAt(v *time.Time) *ActivityUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *ActivityUpdateOne) ClearStartsAt() *ActivityUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *ActivityUpdateOne) SetEndsAt(v time.Time) *ActivityUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableEndsAt(v *time.Time) *ActivityUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *ActivityUpdateOne) ClearEndsAt() *ActivityUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetVisibilityRules sets the "visibility_rules" field.
func (_u *ActivityUpdateOne) SetVisibilityRules(v map[string]interface{}) *ActivityUpdateOne {
	_u.mutation.SetVisibilityRules(v)
	return _u
}

// ClearVisibilityRules clears the value of the "visibility_rules" field.
func (_u *ActivityUpdateOne) ClearVisibilityRules() *ActivityUpdateOne {
	_u.mutation.ClearVisibilityRules()
	return _u
}

// SetParticipationConfig sets the "participation_config" field.
func (_u *ActivityUpdateOne) SetParticipationConfig(v map[string]interface{}) *ActivityUpdateOne {
	_u.mutation.SetParticipationConfig(v)
	return _u
}

// ClearParticipationConfig clears the value of the "participation_config" field.
func (_u *ActivityUpdateOne) ClearParticipationConfig() *ActivityUpdateOne {
	_u.mutation.ClearParticipationConfig()
	return _u
}

// SetActivityConfig sets the "activity_config" field.
func (_u *ActivityUpdateOne) SetActivityConfig(v map[string]interface{}) *ActivityUpdateOne {
	_u.mutation.SetActivityConfig(v)
	return _u
}

// ClearActivityConfig clears the value of the "activity_config" field.
func (_u *ActivityUpdateOne) ClearActivityConfig() *ActivityUpdateOne {
	_u.mutation.ClearActivityConfig()
	return _u
}

// SetTotalParticipations sets the "total_participations" field.
func (_u *ActivityUpdateOne) SetTotalParticipations(v int64) *ActivityUpdateOne {
	_u.mutation.ResetTotalParticipations()
	_u.mutation.SetTotalParticipations(v)
	return _u
}

// SetNillableTotalParticipations sets the "total_participations" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableTotalParticipations(v *int64) *ActivityUpdateOne {
	if v != nil {
		_u.SetTotalParticipations(*v)
	}
	return _u
}

// AddTotalParticipations adds value to the "total_participations" field.
func (_u *ActivityUpdateOne) AddTotalParticipations(v int64) *ActivityUpdateOne {
	_u.mutation.AddTotalParticipations(v)
	return _u
}

// SetTotalRewardsDistributed sets the "total_rewards_distributed" field.
func (_u *ActivityUpdateOne) SetTotalRewardsDistributed(v int64) *ActivityUpdateOne {
	_u.mutation.ResetTotalRewardsDistributed()
	_u.mutation.SetTotalRewardsDistributed(v)
	return _u
}

// SetNillableTotalRewardsDistributed sets the "total_rewards_distributed" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableTotalRewardsDistributed(v *int64) *ActivityUpdateOne {
	if v != nil {
		_u.SetTotalRewardsDistributed(*v)
	}
	return _u
}

// AddTotalRewardsDistributed adds value to the "total_rewards_distributed" field.
func (_u *ActivityUpdateOne) AddTotalRewardsDistributed(v int64) *ActivityUpdateOne {
	_u.mutation.AddTotalRewardsDistributed(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ActivityUpdateOne) SetCreatedBy(v string) *ActivityUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ActivityUpdateOne) SetNillableCreatedBy(v *string) *ActivityUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivityUpdateOne) SetUpdatedAt(v time.Time) *ActivityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRewardIDs adds the "rewards" edge to the ActivityReward entity by IDs.
func (_u *ActivityUpdateOne) AddRewardIDs(ids ...int64) *ActivityUpdateOne {
	_u.mutation.AddRewardIDs(ids...)
	return _u
}

// AddRewards adds the "rewards" edges to the ActivityReward entity.
func (_u *ActivityUpdateOne) AddRewards(v ...*ActivityReward) *ActivityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRewardIDs(ids...)
}

// AddParticipationIDs adds the "participations" edge to the ActivityParticipation entity by IDs.
func (_u *ActivityUpdateOne) AddParticipationIDs(ids ...int64) *ActivityUpdateOne {
	_u.mutation.AddParticipationIDs(ids...)
	return _u
}

// AddParticipations adds the "participations" edges to the ActivityParticipation entity.
func (_u *ActivityUpdateOne) AddParticipations(v ...*ActivityParticipation) *ActivityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipationIDs(ids...)
}

// Mutation returns the ActivityMutation object of the builder.
func (_u *ActivityUpdateOne) Mutation() *ActivityMutation {
	return _u.mutation
}

// ClearRewards clears all "rewards" edges to the ActivityReward entity.
func (_u *ActivityUpdateOne) ClearRewards() *ActivityUpdateOne {
	_u.mutation.ClearRewards()
	return _u
}

// RemoveRewardIDs removes the "rewards" edge to ActivityReward entities by IDs.
func (_u *ActivityUpdateOne) RemoveRewardIDs(ids ...int64) *ActivityUpdateOne {
	_u.mutation.RemoveRewardIDs(ids...)
	return _u
}

// RemoveRewards removes "rewards" edges to ActivityReward entities.
func (_u *ActivityUpdateOne) RemoveRewards(v ...*ActivityReward) *ActivityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRewardIDs(ids...)
}

// ClearParticipations clears all "participations" edges to the ActivityParticipation entity.
func (_u *ActivityUpdateOne) ClearParticipations() *ActivityUpdateOne {
	_u.mutation.ClearParticipations()
	return _u
}

// RemoveParticipationIDs removes the "participations" edge to ActivityParticipation entities by IDs.
func (_u *ActivityUpdateOne) RemoveParticipationIDs(ids ...int64) *ActivityUpdateOne {
	_u.mutation.RemoveParticipationIDs(ids...)
	return _u
}

// RemoveParticipations removes "participations" edges to ActivityParticipation entities.
func (_u *ActivityUpdateOne) RemoveParticipations(v ...*ActivityParticipation) *ActivityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipationIDs(ids...)
}

// Where appends a list predicates to the ActivityUpdate builder.
func (_u *ActivityUpdateOne) Where(ps ...predicate.Activity) *ActivityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivityUpdateOne) Select(field string, fields ...string) *ActivityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Activity entity.
func (_u *ActivityUpdateOne) Save(ctx context.Context) (*Activity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityUpdateOne) SaveX(ctx context.Context) *Activity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := activity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := activity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Activity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := activity.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Activity.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := activity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Activity.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivityUpdateOne) sqlSave(ctx context.Context) (_node *Activity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activity.Table, activity.Columns, sqlgraph.NewFieldSpec(activity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Activity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activity.FieldID)
		for _, f := range fields {
			if !activity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(activity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(activity.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(activity.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(activity.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(activity.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(activity.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(activity.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(activity.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(activity.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(activity.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(activity.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VisibilityRules(); ok {
		_spec.SetField(activity.FieldVisibilityRules, field.TypeJSON, value)
	}
	if _u.mutation.VisibilityRulesCleared() {
		_spec.ClearField(activity.FieldVisibilityRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParticipationConfig(); ok {
		_spec.SetField(activity.FieldParticipationConfig, field.TypeJSON, value)
	}
	if _u.mutation.ParticipationConfigCleared() {
		_spec.ClearField(activity.FieldParticipationConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActivityConfig(); ok {
		_spec.SetField(activity.FieldActivityConfig, field.TypeJSON, value)
	}
	if _u.mutation.ActivityConfigCleared() {
		_spec.ClearField(activity.FieldActivityConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.TotalParticipations(); ok {
		_spec.SetField(activity.FieldTotalParticipations, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalParticipations(); ok {
		_spec.AddField(activity.FieldTotalParticipations, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalRewardsDistributed(); ok {
		_spec.SetField(activity.FieldTotalRewardsDistributed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRewardsDistributed(); ok {
		_spec.AddField(activity.FieldTotalRewardsDistributed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(activity.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRewardsIDs(); len(nodes) > 0 && !_u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.RewardsTable,
			Columns: []string{activity.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ParticipationsTable,
			Columns: []string{activity.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityparticipation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Activity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
