// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/activityreward"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ActivityRewardDelete is the builder for deleting a ActivityReward entity.
type ActivityRewardDelete struct {
	config
	hooks    []Hook
	mutation *ActivityRewardMutation
}

// Where appends a list predicates to the ActivityRewardDelete builder.
func (_d *ActivityRewardDelete) Where(ps ...predicate.ActivityReward) *ActivityRewardDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ActivityRewardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ActivityRewardDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ActivityRewardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(activityreward.Table, sqlgraph.NewFieldSpec(activityreward.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ActivityRewardDeleteOne is the builder for deleting a single ActivityReward entity.
type ActivityRewardDeleteOne struct {
	_d *ActivityRewardDelete
}

// Where appends a list predicates to the ActivityRewardDelete builder.
func (_d *ActivityRewardDeleteOne) Where(ps ...predicate.ActivityReward) *ActivityRewardDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ActivityRewardDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{activityreward.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ActivityRewardDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
