// Code generated by ent, DO NOT EDIT.

package activityparticipation

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the activityparticipation type in the database.
	Label = "activity_participation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldParticipatedAt holds the string denoting the participated_at field in the database.
	FieldParticipatedAt = "participated_at"
	// FieldDailyWindow holds the string denoting the daily_window field in the database.
	FieldDailyWindow = "daily_window"
	// FieldWeeklyWindow holds the string denoting the weekly_window field in the database.
	FieldWeeklyWindow = "weekly_window"
	// FieldMonthlyWindow holds the string denoting the monthly_window field in the database.
	FieldMonthlyWindow = "monthly_window"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldRewardsReceived holds the string denoting the rewards_received field in the database.
	FieldRewardsReceived = "rewards_received"
	// FieldRewardID holds the string denoting the reward_id field in the database.
	FieldRewardID = "reward_id"
	// FieldCostBalance holds the string denoting the cost_balance field in the database.
	FieldCostBalance = "cost_balance"
	// FieldExtraData holds the string denoting the extra_data field in the database.
	FieldExtraData = "extra_data"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeActivity holds the string denoting the activity edge name in mutations.
	EdgeActivity = "activity"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeReward holds the string denoting the reward edge name in mutations.
	EdgeReward = "reward"
	// Table holds the table name of the activityparticipation in the database.
	Table = "activity_participations"
	// ActivityTable is the table that holds the activity relation/edge.
	ActivityTable = "activity_participations"
	// ActivityInverseTable is the table name for the Activity entity.
	// It exists in this package in order to avoid circular dependency with the "activity" package.
	ActivityInverseTable = "activities"
	// ActivityColumn is the table column denoting the activity relation/edge.
	ActivityColumn = "activity_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "activity_participations"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// RewardTable is the table that holds the reward relation/edge.
	RewardTable = "activity_participations"
	// RewardInverseTable is the table name for the ActivityReward entity.
	// It exists in this package in order to avoid circular dependency with the "activityreward" package.
	RewardInverseTable = "activity_rewards"
	// RewardColumn is the table column denoting the reward relation/edge.
	RewardColumn = "reward_id"
)

// Columns holds all SQL columns for activityparticipation fields.
var Columns = []string{
	FieldID,
	FieldActivityID,
	FieldUserID,
	FieldParticipatedAt,
	FieldDailyWindow,
	FieldWeeklyWindow,
	FieldMonthlyWindow,
	FieldResult,
	FieldRewardsReceived,
	FieldRewardID,
	FieldCostBalance,
	FieldExtraData,
	FieldIPAddress,
	FieldUserAgent,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultParticipatedAt holds the default value on creation for the "participated_at" field.
	DefaultParticipatedAt func() time.Time
	// DefaultCostBalance holds the default value on creation for the "cost_balance" field.
	DefaultCostBalance string
	// DefaultIPAddress holds the default value on creation for the "ip_address" field.
	DefaultIPAddress string
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Result defines the type for the "result" enum field.
type Result string

// ResultSuccess is the default value of the Result enum.
const DefaultResult = ResultSuccess

// Result values.
const (
	ResultSuccess Result = "success"
	ResultFailed  Result = "failed"
	ResultPending Result = "pending"
)

func (r Result) String() string {
	return string(r)
}

// ResultValidator is a validator for the "result" field enum values. It is called by the builders before save.
func ResultValidator(r Result) error {
	switch r {
	case ResultSuccess, ResultFailed, ResultPending:
		return nil
	default:
		return fmt.Errorf("activityparticipation: invalid enum value for result field: %q", r)
	}
}

// OrderOption defines the ordering options for the ActivityParticipation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByParticipatedAt orders the results by the participated_at field.
func ByParticipatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParticipatedAt, opts...).ToFunc()
}

// ByDailyWindow orders the results by the daily_window field.
func ByDailyWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyWindow, opts...).ToFunc()
}

// ByWeeklyWindow orders the results by the weekly_window field.
func ByWeeklyWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyWindow, opts...).ToFunc()
}

// ByMonthlyWindow orders the results by the monthly_window field.
func ByMonthlyWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyWindow, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}

// ByRewardID orders the results by the reward_id field.
func ByRewardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardID, opts...).ToFunc()
}

// ByCostBalance orders the results by the cost_balance field.
func ByCostBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostBalance, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByActivityField orders the results by activity field.
func ByActivityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivityStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByRewardField orders the results by reward field.
func ByRewardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRewardStep(), sql.OrderByField(field, opts...))
	}
}
func newActivityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newRewardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RewardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RewardTable, RewardColumn),
	)
}
