// Code generated by ent, DO NOT EDIT.

package activityparticipation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldID, id))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldActivityID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldUserID, v))
}

// ParticipatedAt applies equality check predicate on the "participated_at" field. It's identical to ParticipatedAtEQ.
func ParticipatedAt(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldParticipatedAt, v))
}

// DailyWindow applies equality check predicate on the "daily_window" field. It's identical to DailyWindowEQ.
func DailyWindow(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldDailyWindow, v))
}

// WeeklyWindow applies equality check predicate on the "weekly_window" field. It's identical to WeeklyWindowEQ.
func WeeklyWindow(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldWeeklyWindow, v))
}

// MonthlyWindow applies equality check predicate on the "monthly_window" field. It's identical to MonthlyWindowEQ.
func MonthlyWindow(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldMonthlyWindow, v))
}

// RewardID applies equality check predicate on the "reward_id" field. It's identical to RewardIDEQ.
func RewardID(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldRewardID, v))
}

// CostBalance applies equality check predicate on the "cost_balance" field. It's identical to CostBalanceEQ.
func CostBalance(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldCostBalance, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldIPAddress, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldCreatedAt, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldActivityID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldUserID, vs...))
}

// ParticipatedAtEQ applies the EQ predicate on the "participated_at" field.
func ParticipatedAtEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldParticipatedAt, v))
}

// ParticipatedAtNEQ applies the NEQ predicate on the "participated_at" field.
func ParticipatedAtNEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldParticipatedAt, v))
}

// ParticipatedAtIn applies the In predicate on the "participated_at" field.
func ParticipatedAtIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldParticipatedAt, vs...))
}

// ParticipatedAtNotIn applies the NotIn predicate on the "participated_at" field.
func ParticipatedAtNotIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldParticipatedAt, vs...))
}

// ParticipatedAtGT applies the GT predicate on the "participated_at" field.
func ParticipatedAtGT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldParticipatedAt, v))
}

// ParticipatedAtGTE applies the GTE predicate on the "participated_at" field.
func ParticipatedAtGTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldParticipatedAt, v))
}

// ParticipatedAtLT applies the LT predicate on the "participated_at" field.
func ParticipatedAtLT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldParticipatedAt, v))
}

// ParticipatedAtLTE applies the LTE predicate on the "participated_at" field.
func ParticipatedAtLTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldParticipatedAt, v))
}

// DailyWindowEQ applies the EQ predicate on the "daily_window" field.
func DailyWindowEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldDailyWindow, v))
}

// DailyWindowNEQ applies the NEQ predicate on the "daily_window" field.
func DailyWindowNEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldDailyWindow, v))
}

// DailyWindowIn applies the In predicate on the "daily_window" field.
func DailyWindowIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldDailyWindow, vs...))
}

// DailyWindowNotIn applies the NotIn predicate on the "daily_window" field.
func DailyWindowNotIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldDailyWindow, vs...))
}

// DailyWindowGT applies the GT predicate on the "daily_window" field.
func DailyWindowGT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldDailyWindow, v))
}

// DailyWindowGTE applies the GTE predicate on the "daily_window" field.
func DailyWindowGTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldDailyWindow, v))
}

// DailyWindowLT applies the LT predicate on the "daily_window" field.
func DailyWindowLT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldDailyWindow, v))
}

// DailyWindowLTE applies the LTE predicate on the "daily_window" field.
func DailyWindowLTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldDailyWindow, v))
}

// WeeklyWindowEQ applies the EQ predicate on the "weekly_window" field.
func WeeklyWindowEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldWeeklyWindow, v))
}

// WeeklyWindowNEQ applies the NEQ predicate on the "weekly_window" field.
func WeeklyWindowNEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldWeeklyWindow, v))
}

// WeeklyWindowIn applies the In predicate on the "weekly_window" field.
func WeeklyWindowIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldWeeklyWindow, vs...))
}

// WeeklyWindowNotIn applies the NotIn predicate on the "weekly_window" field.
func WeeklyWindowNotIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldWeeklyWindow, vs...))
}

// WeeklyWindowGT applies the GT predicate on the "weekly_window" field.
func WeeklyWindowGT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldWeeklyWindow, v))
}

// WeeklyWindowGTE applies the GTE predicate on the "weekly_window" field.
func WeeklyWindowGTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldWeeklyWindow, v))
}

// WeeklyWindowLT applies the LT predicate on the "weekly_window" field.
func WeeklyWindowLT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldWeeklyWindow, v))
}

// WeeklyWindowLTE applies the LTE predicate on the "weekly_window" field.
func WeeklyWindowLTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldWeeklyWindow, v))
}

// MonthlyWindowEQ applies the EQ predicate on the "monthly_window" field.
func MonthlyWindowEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldMonthlyWindow, v))
}

// MonthlyWindowNEQ applies the NEQ predicate on the "monthly_window" field.
func MonthlyWindowNEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldMonthlyWindow, v))
}

// MonthlyWindowIn applies the In predicate on the "monthly_window" field.
func MonthlyWindowIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldMonthlyWindow, vs...))
}

// MonthlyWindowNotIn applies the NotIn predicate on the "monthly_window" field.
func MonthlyWindowNotIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldMonthlyWindow, vs...))
}

// MonthlyWindowGT applies the GT predicate on the "monthly_window" field.
func MonthlyWindowGT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldMonthlyWindow, v))
}

// MonthlyWindowGTE applies the GTE predicate on the "monthly_window" field.
func MonthlyWindowGTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldMonthlyWindow, v))
}

// MonthlyWindowLT applies the LT predicate on the "monthly_window" field.
func MonthlyWindowLT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldMonthlyWindow, v))
}

// MonthlyWindowLTE applies the LTE predicate on the "monthly_window" field.
func MonthlyWindowLTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldMonthlyWindow, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v Result) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v Result) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...Result) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...Result) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldResult, vs...))
}

// RewardsReceivedIsNil applies the IsNil predicate on the "rewards_received" field.
func RewardsReceivedIsNil() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIsNull(FieldRewardsReceived))
}

// RewardsReceivedNotNil applies the NotNil predicate on the "rewards_received" field.
func RewardsReceivedNotNil() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotNull(FieldRewardsReceived))
}

// RewardIDEQ applies the EQ predicate on the "reward_id" field.
func RewardIDEQ(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldRewardID, v))
}

// RewardIDNEQ applies the NEQ predicate on the "reward_id" field.
func RewardIDNEQ(v int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldRewardID, v))
}

// RewardIDIn applies the In predicate on the "reward_id" field.
func RewardIDIn(vs ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldRewardID, vs...))
}

// RewardIDNotIn applies the NotIn predicate on the "reward_id" field.
func RewardIDNotIn(vs ...int64) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldRewardID, vs...))
}

// RewardIDIsNil applies the IsNil predicate on the "reward_id" field.
func RewardIDIsNil() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIsNull(FieldRewardID))
}

// RewardIDNotNil applies the NotNil predicate on the "reward_id" field.
func RewardIDNotNil() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotNull(FieldRewardID))
}

// CostBalanceEQ applies the EQ predicate on the "cost_balance" field.
func CostBalanceEQ(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldCostBalance, v))
}

// CostBalanceNEQ applies the NEQ predicate on the "cost_balance" field.
func CostBalanceNEQ(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldCostBalance, v))
}

// CostBalanceIn applies the In predicate on the "cost_balance" field.
func CostBalanceIn(vs ...string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldCostBalance, vs...))
}

// CostBalanceNotIn applies the NotIn predicate on the "cost_balance" field.
func CostBalanceNotIn(vs ...string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldCostBalance, vs...))
}

// CostBalanceGT applies the GT predicate on the "cost_balance" field.
func CostBalanceGT(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldCostBalance, v))
}

// CostBalanceGTE applies the GTE predicate on the "cost_balance" field.
func CostBalanceGTE(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldCostBalance, v))
}

// CostBalanceLT applies the LT predicate on the "cost_balance" field.
func CostBalanceLT(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldCostBalance, v))
}

// CostBalanceLTE applies the LTE predicate on the "cost_balance" field.
func CostBalanceLTE(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldCostBalance, v))
}

// CostBalanceContains applies the Contains predicate on the "cost_balance" field.
func CostBalanceContains(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldContains(FieldCostBalance, v))
}

// CostBalanceHasPrefix applies the HasPrefix predicate on the "cost_balance" field.
func CostBalanceHasPrefix(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldHasPrefix(FieldCostBalance, v))
}

// CostBalanceHasSuffix applies the HasSuffix predicate on the "cost_balance" field.
func CostBalanceHasSuffix(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldHasSuffix(FieldCostBalance, v))
}

// CostBalanceEqualFold applies the EqualFold predicate on the "cost_balance" field.
func CostBalanceEqualFold(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEqualFold(FieldCostBalance, v))
}

// CostBalanceContainsFold applies the ContainsFold predicate on the "cost_balance" field.
func CostBalanceContainsFold(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldContainsFold(FieldCostBalance, v))
}

// ExtraDataIsNil applies the IsNil predicate on the "extra_data" field.
func ExtraDataIsNil() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIsNull(FieldExtraData))
}

// ExtraDataNotNil applies the NotNil predicate on the "extra_data" field.
func ExtraDataNotNil() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotNull(FieldExtraData))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldContainsFold(FieldIPAddress, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.FieldLTE(FieldCreatedAt, v))
}

// HasActivity applies the HasEdge predicate on the "activity" edge.
func HasActivity() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivityWith applies the HasEdge predicate on the "activity" edge with a given conditions (other predicates).
func HasActivityWith(preds ...predicate.Activity) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(func(s *sql.Selector) {
		step := newActivityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReward applies the HasEdge predicate on the "reward" edge.
func HasReward() predicate.ActivityParticipation {
	return predicate.ActivityParticipation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RewardTable, RewardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRewardWith applies the HasEdge predicate on the "reward" edge with a given conditions (other predicates).
func HasRewardWith(preds ...predicate.ActivityReward) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(func(s *sql.Selector) {
		step := newRewardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActivityParticipation) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActivityParticipation) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActivityParticipation) predicate.ActivityParticipation {
	return predicate.ActivityParticipation(sql.NotPredicates(p))
}
